<script lang="ts">
  import { tick } from "svelte";
  import type { AdapterPromise, AgentProvisionOptionsView } from "@hq/platform";
  import type { EntryPointResult, EntryPointTarget, CloudBotDraft } from "../lifecycle-entry-points.js";
  import { botHandle, cloudNameIssue, firstSignedInCloudRuntime, type BotRuntime } from "./create-bot-model.js";

  type Company = { companyUid: string; label: string };
  export interface NewBotCreated { name: string; companyUid: string; brain: BotRuntime; target: EntryPointTarget; }
  interface Props {
    companies: readonly Company[]; currentCompanyUid?: string | null; runtimeReady?: Record<string, boolean> | null;
    loadProvisionOptions: (companyUid: string) => AdapterPromise<AgentProvisionOptionsView>;
    oncreate: (companyUid: string, draft: CloudBotDraft) => Promise<EntryPointResult>;
    oncomplete: (created: NewBotCreated) => void; onopenlocal?: (() => void) | null;
  }
  let { companies, currentCompanyUid = null, runtimeReady = null, loadProvisionOptions, oncreate, oncomplete, onopenlocal = null }: Props = $props();
  const initialCompany = (companies.find((company) => company.companyUid === currentCompanyUid) ?? companies[0])?.companyUid ?? "";
  let companyUid = $state(initialCompany); let name = $state(""); let runtime = $state<BotRuntime>(firstSignedInCloudRuntime(runtimeReady));
  let options = $state<AgentProvisionOptionsView | null>(null); let quoteStatus = $state<"loading" | "ready" | "error">("loading");
  let selectedSize = $state<"basic" | "power" | "dev" | "">(""); let runtimeChosen = $state(false); let moreOptions = $state(false);
  let attempted = $state(false); let busy = $state(false); let refusal = $state<string | null>(null); let step = $state<1 | 2 | 3>(1); let quoteGeneration = 0;
  const singleCompany = $derived(companies.length === 1); const finalStep = $derived(singleCompany ? 2 : 3);
  const derivedHandle = $derived(botHandle({ name, handle: "" })); const nameIssue = $derived(cloudNameIssue(name));
  const selectedOption = $derived(options?.options.find((option) => option.key === selectedSize) ?? null);
  const defaultOption = $derived(options?.options.find((option) => option.default && option.selectable && option.netMonthlyCents !== null) ?? null);
  const canSubmit = $derived(!busy && !!companyUid && !!selectedOption?.selectable && selectedOption.netMonthlyCents !== null && quoteStatus === "ready");
  const canCreate = $derived(canSubmit && !nameIssue);
  function monthly(cents: number): string { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100); }
  function optionPrice(option: AgentProvisionOptionsView["options"][number]): string { return option.notBilled || option.netMonthlyCents === 0 ? "Included for your company" : option.netMonthlyCents === null ? "Price unavailable" : `${monthly(option.netMonthlyCents)}/month`; }
  function focusStep(): void { void tick().then(() => document.querySelector<HTMLElement>(`[data-testid="new-bot-step-${step}"] input:not([disabled]), [data-testid="new-bot-step-${step}"] button:not([disabled])`)?.focus()); }
  function go(next: 1 | 2 | 3): void { refusal = null; step = next; focusStep(); }
  function continueName(): void { attempted = true; if (!nameIssue) go(2); }
  function chooseSizeAfterLoad(value: AgentProvisionOptionsView): void { const preferred = value.options.find((option) => option.default && option.selectable && option.netMonthlyCents !== null) ?? value.options.find((option) => option.selectable && option.netMonthlyCents !== null); selectedSize = preferred?.key ?? ""; }
  $effect(() => { if (!runtimeChosen) runtime = firstSignedInCloudRuntime(runtimeReady); });
  $effect(() => { const uid = companyUid.trim(); const generation = ++quoteGeneration; options = null; quoteStatus = uid ? "loading" : "error"; if (!uid) return; let active = true; void loadProvisionOptions(uid).then((result) => { if (!active || generation !== quoteGeneration || !result.ok || !Array.isArray(result.value.options)) { if (active && generation === quoteGeneration) quoteStatus = "error"; return; } options = result.value; quoteStatus = "ready"; chooseSizeAfterLoad(result.value); }).catch(() => { if (active && generation === quoteGeneration) quoteStatus = "error"; }); return () => { active = false; }; });
  $effect(() => { focusStep(); });
  async function submit(): Promise<void> { attempted = true; refusal = null; if (!canCreate || busy) return; busy = true; const result = await oncreate(companyUid, { name: name.trim(), handle: derivedHandle, runtime, size: selectedSize as "basic" | "power" | "dev", authMode: "subscription" }).catch((): EntryPointResult => ({ ok: false, blocked: false, reason: "We couldn't create this bot. Try again in a moment." })); busy = false; if (result.ok) { oncomplete({ name: name.trim(), companyUid, brain: runtime, target: result.target }); return; } const message = result.reason.trim() || "We couldn't create this bot. Try again in a moment."; refusal = message.match(/^.*?[.!?](?:\s|$)/)?.[0].trim() || message; }
  function onKeydown(event: KeyboardEvent): void { if (event.key !== "Enter" || busy) return; const target = event.target as HTMLElement; if (target.tagName === "BUTTON") return; event.preventDefault(); if (step === 1) continueName(); else if (step < finalStep) go((step + 1) as 2 | 3); else void submit(); }
</script>

<div class="new-bot-create" data-testid="new-bot-create-screen" role="group" onkeydown={onKeydown}>
  <div class="new-bot-progress" aria-label={`Step ${step} of ${finalStep}`}>{#each Array(finalStep) as _, index}<span class:active={index + 1 === step}></span>{/each}</div>
  {#if step === 1}
    <section class="new-bot-step" data-testid="new-bot-step-1"><p class="new-bot-takeover-kicker">A new teammate</p><h1 id="new-bot-takeover-title">Enter a <em>name.</em></h1><p class="new-bot-create-copy">This is how your new teammate will appear in HQ.</p><label class="new-bot-create-label" for="new-bot-name">Name</label><input id="new-bot-name" class="new-bot-create-input" data-testid="new-bot-name" value={name} aria-invalid={attempted && nameIssue ? "true" : undefined} aria-describedby="new-bot-create-issue" autocomplete="off" oninput={(event) => { name = (event.currentTarget as HTMLInputElement).value; }} />{#if attempted && nameIssue}<p id="new-bot-create-issue" class="new-bot-create-error" role="alert">{nameIssue}</p>{/if}<button type="button" class="new-bot-create-submit" data-testid="new-bot-continue-name" onclick={continueName}>Continue</button>{#if onopenlocal}<button type="button" class="new-bot-takeover-local" data-testid="new-bot-takeover-local" onclick={onopenlocal}>Create a local bot instead</button>{/if}</section>
  {:else if step === 2}
    <section class="new-bot-step" data-testid="new-bot-step-2"><button type="button" class="new-bot-back" onclick={() => go(1)}>Back</button><p class="new-bot-takeover-kicker">Choose a brain</p><h1>Pick the <em>brain.</em></h1><p class="new-bot-create-copy">Choose the model your teammate will use.</p><fieldset class="new-bot-brains" disabled={busy}><legend class="sr-only">Brain</legend>{#each (["codex", "claude", "grok"] as const) as choice}<label class:selected={runtime === choice} class="new-bot-brain"><input type="radio" name="new-bot-brain" value={choice} checked={runtime === choice} onchange={() => { runtimeChosen = true; runtime = choice; }} /><span>{choice === "codex" ? "Codex" : choice === "claude" ? "Claude" : "Grok"}</span>{#if runtimeReady?.[choice] === true}<small>Signed in on this Mac</small>{/if}</label>{/each}</fieldset>{#if singleCompany}{#if refusal}<p id="new-bot-create-issue" class="new-bot-create-error" role="alert">{refusal}</p>{/if}<button type="button" class="new-bot-create-submit" data-testid="new-bot-create-submit" disabled={!canSubmit} aria-busy={busy ? "true" : undefined} onclick={() => void submit()}>{busy ? "Creating bot..." : "Create bot"}</button>{#if defaultOption}<p class="new-bot-price" data-testid="new-bot-default-price">{optionPrice(defaultOption)} for {defaultOption.productName}.</p>{/if}{:else}<button type="button" class="new-bot-create-submit" data-testid="new-bot-continue-brain" onclick={() => go(3)}>Continue</button>{/if}</section>
  {:else}
    <section class="new-bot-step" data-testid="new-bot-step-3"><button type="button" class="new-bot-back" onclick={() => go(2)}>Back</button><p class="new-bot-takeover-kicker">Your workspace</p><h1>Choose a <em>company.</em></h1><p class="new-bot-create-copy">Your bot will work with this company from the start.</p><div class="new-bot-companies" role="radiogroup" aria-label="Company">{#each companies as company (company.companyUid)}<label class:selected={companyUid === company.companyUid} class="new-bot-company"><input type="radio" name="new-bot-company" value={company.companyUid} checked={companyUid === company.companyUid} disabled={busy} onchange={() => { companyUid = company.companyUid; }} /><span>{company.label}</span></label>{/each}</div>{#if refusal}<p id="new-bot-create-issue" class="new-bot-create-error" role="alert">{refusal}</p>{/if}<button type="button" class="new-bot-more" aria-expanded={moreOptions} onclick={() => (moreOptions = !moreOptions)}>More options</button>{#if moreOptions}<fieldset class="new-bot-sizes" disabled={busy || quoteStatus !== "ready"}><legend class="new-bot-create-label">Machine size</legend>{#each options?.options ?? [] as option (option.key)}<label class:selected={selectedSize === option.key} class="new-bot-size"><input type="radio" name="new-bot-size" value={option.key} checked={selectedSize === option.key} disabled={!option.selectable || option.netMonthlyCents === null} onchange={() => (selectedSize = option.key)} /><span>{option.productName} · {optionPrice(option)}</span></label>{:else}<span class="new-bot-muted">{quoteStatus === "loading" ? "Loading server options..." : "Server options could not be loaded."}</span>{/each}</fieldset>{/if}<button type="button" class="new-bot-create-submit" data-testid="new-bot-create-submit" disabled={!canSubmit} aria-busy={busy ? "true" : undefined} onclick={() => void submit()}>{busy ? "Creating bot..." : "Create bot"}</button>{#if defaultOption}<p class="new-bot-price" data-testid="new-bot-default-price">{optionPrice(defaultOption)} for {defaultOption.productName}.</p>{:else if quoteStatus === "loading"}<p class="new-bot-price" aria-live="polite">Loading the server's default price...</p>{/if}</section>
  {/if}
</div>
