/**
 * Sample Outpost for tests only. The page never imports this; it reads the
 * signed-in user's Outpost from hq-pro (see outpost-live.ts).
 */
import type { OutpostCache } from "./outpost-model.js";

export function fixtureOutpost(now: number = Date.now()): OutpostCache {
  const at = (deltaMs: number) => new Date(now + deltaMs).toISOString();
  return {
    provisioned: true,
    host: {
      name: "corey-outpost",
      hostname: "corey-outpost.hq-outpost.net",
      region: "us-east-1",
      instance: "t3.large · 2 vCPU · 8 GB · 80 GB auto-grow",
      online: true,
      heartbeatAgo: "12 s ago",
      lastHeartbeatAt: "10:52",
      lastHeartbeatIso: at(-14 * 60_000),
      uptime: "41 d 6 h",
      cpuPct: 18,
      memUsed: "4.3",
      memTotal: "8 GB",
      diskUsed: "29",
      diskTotal: "80 GB",
      version: "0.10.287",
      identity: "corey-outpost",
    },
    jobs: [
      {
        id: "standup-brief",
        name: "standup-brief",
        detail: "Claude · skill indigo:standup-brief · posts to #dev-standup",
        runtime: "Claude",
        cadence: "weekdays",
        cadenceLabel: "weekdays 09:00 PT",
        cron: "0 9 * * 1-5",
        timezone: "America/Los_Angeles",
        nextRun: "tomorrow 09:00",
        lastResult: "ok · today 09:00 · 38s",
        lastRunAt: at(-2 * 3_600_000),
        lastResultNote: "38s",
        status: "ok",
        paused: false,
        alert: "dm",
        alertWhen: "always",
        mode: "skill",
        prompt: "",
        skill: "indigo:standup-brief",
        args: "",
        secretNames: [],
      },
      {
        id: "attio-call-sync",
        name: "attio-call-sync",
        detail: "Codex · prompt · call notes into Attio · secret missing on Outpost",
        runtime: "Codex",
        cadence: "hourly",
        cadenceLabel: "hourly",
        cron: "0 * * * *",
        timezone: "America/Los_Angeles",
        nextRun: "in 33m",
        nextRunAt: at(33 * 60_000),
        lastResult: "failed · 19m ago · 3 in a row",
        lastRunAt: at(-19 * 60_000),
        lastResultNote: "3 in a row",
        status: "failed",
        paused: false,
        alert: "dm",
        alertWhen: "on fail",
        mode: "prompt",
        prompt: "Sync today's call notes into Attio and DM Corey a one-line summary.",
        skill: "indigo:attio-call-sync",
        args: "--since today --dm corey",
        secretNames: ["ATTIO_API_KEY"],
      },
      {
        id: "knowledge-pulse",
        name: "knowledge-pulse",
        detail: "Claude · skill knowledge-pulse · paused Sep 20",
        runtime: "Claude",
        cadence: "weekly",
        cadenceLabel: "weekly Mon 07:00 PT",
        cron: "0 7 * * 1",
        timezone: "America/Los_Angeles",
        nextRun: "paused",
        lastResult: "ok · 11d ago · 2m 02s",
        status: "ok",
        paused: true,
        alert: "none",
        alertWhen: "on fail",
        mode: "skill",
        prompt: "",
        skill: "knowledge-pulse",
        args: "",
        secretNames: [],
      },
    ],
    runs: [
      { id: "r1", jobId: "standup-brief", job: "standup-brief", when: "2h ago", at: at(-2 * 3_600_000), detail: "38s · posted to #dev-standup", status: "ok" },
      { id: "r2", jobId: "attio-call-sync", job: "attio-call-sync", when: "19m ago", at: at(-19 * 60_000), detail: "0.8s · secret ATTIO_API_KEY not readable on Outpost", status: "failed" },
      { id: "r3", jobId: "attio-call-sync", job: "attio-call-sync", when: "1h ago", at: at(-79 * 60_000), detail: "0.8s · same error", status: "failed" },
    ],
    logs: [
      { id: "l1", t: "09:00:01.012", level: "info", job: "standup-brief", message: "job start · claude · skill indigo:standup-brief" },
      { id: "l2", t: "09:15:02.790", level: "err", job: "attio-call-sync", message: "secret ATTIO_API_KEY · not readable by corey-outpost" },
      { id: "l3", t: "09:41:17.558", level: "info", job: "outpost", message: "heartbeat ok · cpu 14%" },
    ],
    unreachable: false,
    retryInSec: 22,
    retryAttempt: 6,
    fetchedAt: null,
  };
}
