/**
 * Design-fixture snapshot for My Telemetry (US-032 scenes).
 * Costs on the model rows are list-rate estimates (see LIST_RATES).
 */
import {
  formatUsd,
  listRateUsd,
  type ModelUsage,
  type TelemetrySnapshot,
} from "./telemetry-model.js";

const models: ModelUsage[] = [
  {
    model: "opus",
    label: "Opus 4.1",
    hint: "plans, reviews",
    input: 280_000,
    output: 90_000,
    cacheWrite: 80_000,
    cacheRead: 1_150_000,
  },
  {
    model: "sonnet",
    label: "Sonnet 4.5",
    hint: "stories, bots",
    input: 820_000,
    output: 28_000,
    cacheWrite: 210_000,
    cacheRead: 1_502_000,
  },
  {
    model: "haiku",
    label: "Haiku 4.5",
    hint: "probes, routing",
    input: 18_000,
    output: 4_000,
    cacheWrite: 6_000,
    cacheRead: 14_000,
  },
];

function cost(model: ModelUsage["model"]): number {
  const row = models.find((m) => m.model === model);
  return row ? listRateUsd(row) : 0;
}

const listCostUsd = models.reduce((sum, row) => sum + listRateUsd(row), 0);

function day(opus: number, sonnet: number, haiku: number, today = false) {
  return { label: "", opus, sonnet, haiku, today };
}

export const TELEMETRY_SMOKE: TelemetrySnapshot = {
  range: "30d",
  rangeLabel: "Sep 2 – Oct 1",
  subtitle: "you and the bots acting as you",
  sessions: 128,
  sessionsDelta: "+12%",
  tokensLabel: "4.2M",
  tokensDelta: "+9% vs Aug",
  modelMix: "38% Opus · 61% Sonnet · 1% Haiku",
  storiesShipped: 19,
  deploys: 7,
  distinctSkills: 31,
  medianGap: "6h 40m",
  perDay: "140k",
  perSession: "33k",
  cacheReadShare: "61%",
  listCostUsd,
  peakLabel: "peak 412k · Sep 24",
  dayLabels: ["Sep 2", "Sep 9", "Sep 16", "Sep 23", "today"],
  days: [
    day(90, 58, 8),
    day(74, 78, 4),
    day(49, 41, 8),
    day(37, 33, 4),
    day(99, 62, 8),
    day(123, 95, 8),
    day(66, 82, 4),
    day(82, 74, 8),
    day(41, 49, 4),
    day(107, 78, 8),
    day(86, 58, 4),
    day(144, 107, 8),
    day(127, 111, 12),
    day(33, 49, 12),
    day(70, 78, 8),
    day(95, 82, 4),
    day(78, 127, 12),
    day(111, 115, 8),
    day(29, 66, 12),
    day(103, 123, 8),
    day(21, 58, 4),
    day(115, 70, 8),
    day(214, 173, 16),
    day(49, 58, 8),
    day(90, 78, 4),
    day(86, 41, 8),
    day(74, 99, 8),
    day(123, 131, 12),
    day(181, 156, 12),
    day(140, 168, 8, true),
  ],
  skills: [
    { name: "/storyboard", count: 22 },
    { name: "/execute-task", count: 17 },
    { name: "/deploy", count: 14 },
    { name: "/handoff", count: 11 },
    { name: "indigo:standup-brief", count: 9 },
    { name: "personal:cut30", count: 7 },
    { name: "/review", count: 6 },
  ],
  bots: [
    { name: "deacon", meta: "hq-desktop-app · 41 sessions · 1.1M tok", status: "live · 14m", live: true },
    { name: "nightly-qa", meta: "Outpost · 30 runs · 212k tokens", status: "running", live: true },
    { name: "Maggie", meta: "cut30 council · 12 sessions · 88k tok", status: "idle · 2d", live: false },
    { name: "sync-docs", meta: "indigo-docs · 4 runs · 36k tokens", status: "idle · 1d", live: false },
  ],
  models,
  byCompany: [
    { id: "indigo", label: "Indigo", mark: "IN", bot: false, meta: "91 sessions", tokens: 3_020_000, costUsd: listCostUsd * 0.72 },
    { id: "lr", label: "LiveRecover", mark: "LR", bot: false, meta: "24 sessions", tokens: 800_000, costUsd: listCostUsd * 0.19 },
    { id: "personal", label: "Personal", mark: "CE", bot: false, meta: "13 sessions", tokens: 380_000, costUsd: listCostUsd * 0.09 },
  ],
  byActor: [
    { id: "you", label: "You", mark: "CE", bot: false, meta: "laptop", tokens: 2_640_000, costUsd: listCostUsd * 0.63 },
    { id: "deacon", label: "deacon", mark: "⌁", bot: true, meta: "41 sessions", tokens: 1_100_000, costUsd: listCostUsd * 0.26 },
    { id: "qa", label: "nightly-qa", mark: "⌁", bot: true, meta: "Outpost", tokens: 210_000, costUsd: listCostUsd * 0.05 },
    { id: "fleet", label: "scout, ledger", mark: "⌁", bot: true, meta: "fleet", tokens: 250_000, costUsd: listCostUsd * 0.06 },
  ],
  io: { input: "1.12M", cacheRead: "2.67M", cacheWrite: "0.30M", output: "0.12M" },
  outcomeCounts: {
    all: 128,
    live: 1,
    deployed: 7,
    deployedMeta: "5 live · 1 sleeping · 1 failed",
    shipped: 19,
    shippedMeta: "stories merged · 11 Indigo · 8 LR",
    blocked: 4,
    blockedMeta: "2 need a decision from you",
    none: 31,
    noneMeta: "reads, lookups, probes",
  },
  mix: { deployed: 6, shipped: 15, blocked: 3, none: 24, other: 52 },
  sessionsRows: [
    {
      id: "s1",
      when: "now",
      day: "Today",
      company: "Indigo",
      mark: "IN",
      project: "hq-desktop-console-rail",
      detail: "storyboard",
      host: "MacBook Pro",
      length: "2h 14m",
      tokensLabel: "318k",
      tokens: 318_000,
      outcome: "in progress",
      outcomeKind: "live",
      actor: "you",
      failed: false,
      outcomeBucket: "live",
      openLabel: "session",
      costLabel: formatUsd(4.12),
      tokensIn: "241k in",
      tokensOut: "77k out",
      branch: "design/console-rail-v2",
      skills: ["/storyboard", "/diagram", "/humanize", "/checkpoint"],
      timeline: [
        { at: "10:02", text: "Session opened · indigo context loaded" },
        { at: "10:09", text: "/storyboard · revision 8 audit read" },
        { at: "10:41", text: "3 fan-out agents started · scenes u, v, w" },
        { at: "11:30", text: "/checkpoint · thread file written" },
        { at: "now", text: "Rendering scene PNGs", live: true },
      ],
      modelSplit: { opus: 44, sonnet: 54, haiku: 2 },
    },
    {
      id: "s2",
      when: "9:31 AM",
      day: "Today",
      company: "Indigo",
      mark: "IN",
      project: "hq-desktop-app",
      detail: "via deacon",
      host: "deacon · fleet",
      length: "46m",
      tokensLabel: "141k",
      tokens: 141_000,
      outcome: "branch pushed",
      outcomeKind: "ok",
      actor: "bot",
      failed: false,
      outcomeBucket: "other",
      openLabel: "session",
      costLabel: formatUsd(1.8),
      tokensIn: "100k in",
      tokensOut: "41k out",
      branch: "feat/console-rail",
      skills: ["/execute-task"],
      timeline: [{ at: "9:31", text: "Branch pushed" }],
      modelSplit: { opus: 20, sonnet: 78, haiku: 2 },
    },
    {
      id: "s3",
      when: "8:02 AM",
      day: "Today",
      company: "Personal",
      mark: "CE",
      project: "cut30",
      detail: "week plan",
      host: "MacBook Pro",
      length: "18m",
      tokensLabel: "22k",
      tokens: 22_000,
      outcome: "deployed",
      outcomeKind: "ok",
      actor: "you",
      failed: false,
      outcomeBucket: "deployed",
      openLabel: "deployment",
      costLabel: formatUsd(0.4),
      tokensIn: "16k in",
      tokensOut: "6k out",
      branch: "main",
      skills: ["personal:cut30"],
      timeline: [{ at: "8:02", text: "Deployed cut30-week-41.hq.run" }],
      modelSplit: { opus: 10, sonnet: 88, haiku: 2 },
    },
    {
      id: "s4",
      when: "6:00 AM",
      day: "Today",
      company: "Indigo",
      mark: "IN",
      project: "daily-pulse",
      detail: "scheduled",
      host: "Outpost",
      length: "3m",
      tokensLabel: "11k",
      tokens: 11_000,
      outcome: "report posted",
      outcomeKind: "ok",
      actor: "outpost",
      failed: false,
      outcomeBucket: "other",
      openLabel: "session",
      costLabel: formatUsd(0.12),
      tokensIn: "8k in",
      tokensOut: "3k out",
      branch: "main",
      skills: ["indigo:daily-pulse"],
      timeline: [{ at: "6:00", text: "Report posted" }],
      modelSplit: { opus: 0, sonnet: 40, haiku: 60 },
    },
    {
      id: "s5",
      when: "yesterday",
      day: "Yesterday",
      company: "LiveRecover",
      mark: "LR",
      project: "dunning-reconcile",
      detail: "US-003",
      host: "MacBook Pro",
      length: "1h 05m",
      tokensLabel: "96k",
      tokens: 96_000,
      outcome: "story shipped",
      outcomeKind: "ok",
      actor: "you",
      failed: false,
      outcomeBucket: "shipped",
      openLabel: "story",
      costLabel: formatUsd(1.1),
      tokensIn: "70k in",
      tokensOut: "26k out",
      branch: "feat/dunning-grace",
      skills: ["/execute-task"],
      timeline: [{ at: "4:12", text: "PR #212 merged" }],
      modelSplit: { opus: 30, sonnet: 68, haiku: 2 },
    },
    {
      id: "s6",
      when: "yesterday",
      day: "Yesterday",
      company: "Indigo",
      mark: "IN",
      project: "standup-brief",
      detail: "via deacon",
      host: "deacon · fleet",
      length: "6m",
      tokensLabel: "31k",
      tokens: 31_000,
      outcome: "deployed",
      outcomeKind: "ok",
      actor: "bot",
      failed: false,
      outcomeBucket: "deployed",
      openLabel: "deployment",
      costLabel: formatUsd(0.35),
      tokensIn: "22k in",
      tokensOut: "9k out",
      branch: "main",
      skills: ["indigo:standup-brief"],
      timeline: [{ at: "10:40", text: "Deployed standup report" }],
      modelSplit: { opus: 15, sonnet: 80, haiku: 5 },
    },
    {
      id: "s7",
      when: "Sep 29",
      day: "Sep 29",
      company: "Indigo",
      mark: "IN",
      project: "ontology",
      detail: "explorer deploy",
      host: "MacBook Pro",
      length: "24m",
      tokensLabel: "58k",
      tokens: 58_000,
      outcome: "deploy failed",
      outcomeKind: "error",
      actor: "you",
      failed: true,
      outcomeBucket: "blocked",
      openLabel: "logs",
      costLabel: formatUsd(0.7),
      tokensIn: "40k in",
      tokensOut: "18k out",
      branch: "feat/ontology",
      skills: ["/deploy"],
      timeline: [{ at: "5:48", text: "Deploy failed · build step exited 1" }],
      modelSplit: { opus: 40, sonnet: 58, haiku: 2 },
    },
    {
      id: "s8",
      when: "Sep 29",
      day: "Sep 29",
      company: "Indigo",
      mark: "IN",
      project: "crm-management",
      detail: "Attio sync",
      host: "MacBook Pro",
      length: "12m",
      tokensLabel: "19k",
      tokens: 19_000,
      outcome: "no changes",
      outcomeKind: "dim",
      actor: "you",
      failed: false,
      outcomeBucket: "none",
      openLabel: "session",
      costLabel: formatUsd(0.2),
      tokensIn: "14k in",
      tokensOut: "5k out",
      branch: "main",
      skills: ["indigo:crm-management"],
      timeline: [{ at: "2:03", text: "14 records checked, 0 drift" }],
      modelSplit: { opus: 10, sonnet: 85, haiku: 5 },
    },
    {
      id: "s9",
      when: "Sep 28",
      day: "Sep 28",
      company: "Personal",
      mark: "CE",
      project: "hq-sync-test-macos",
      detail: "",
      host: "MacBook Pro",
      length: "52m",
      tokensLabel: "77k",
      tokens: 77_000,
      outcome: "story shipped",
      outcomeKind: "ok",
      actor: "you",
      failed: false,
      outcomeBucket: "shipped",
      openLabel: "story",
      costLabel: formatUsd(0.9),
      tokensIn: "55k in",
      tokensOut: "22k out",
      branch: "feat/rescue",
      skills: ["/execute-task"],
      timeline: [{ at: "3:30", text: "PR #88 merged" }],
      modelSplit: { opus: 35, sonnet: 63, haiku: 2 },
    },
    {
      id: "s10",
      when: "Sep 26",
      day: "Sep 26",
      company: "LiveRecover",
      mark: "LR",
      project: "lr-meta-funnel-daily",
      detail: "via nightly-qa",
      host: "Outpost",
      length: "4m",
      tokensLabel: "9k",
      tokens: 9_000,
      outcome: "report posted",
      outcomeKind: "ok",
      actor: "outpost",
      failed: false,
      outcomeBucket: "other",
      openLabel: "session",
      costLabel: formatUsd(0.08),
      tokensIn: "7k in",
      tokensOut: "2k out",
      branch: "main",
      skills: ["liverecover:lr-meta-funnel-daily"],
      timeline: [{ at: "11:58", text: "Report posted" }],
      modelSplit: { opus: 0, sonnet: 30, haiku: 70 },
    },
  ],
};

export const SMOKE_LIST_COST_LABEL = formatUsd(listCostUsd);

export const TELEMETRY_SCOPES = [
  { id: "all", label: "All my work", mark: "", count: 128 },
  { id: "indigo", label: "Indigo", mark: "IN", count: 91 },
  { id: "lr", label: "LiveRecover", mark: "LR", count: 24 },
  { id: "personal", label: "Personal", mark: "CE", count: 13 },
] as const;
