import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

/**
 * Config guards for the mobile native shell.
 *
 * `svelte.config.js` selects the server hook on `process.env.TAURI`: set means
 * the empty Tauri hook, unset means the Cognito/session web hook plus the
 * hosted route handlers. So a mobile command that forgets `TAURI=1` silently
 * runs the phone against the WEB auth path, which the static mobile build does
 * not ship. That is invisible until sign-in fails on a device, so it is pinned
 * here instead.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = resolve(HERE, "../..");

const pkg = JSON.parse(readFileSync(resolve(APP, "package.json"), "utf8")) as {
  scripts: Record<string, string>;
};
const conf = JSON.parse(
  readFileSync(resolve(APP, "src-tauri/tauri.conf.json"), "utf8"),
) as { build: Record<string, string>; identifier: string };
/**
 * Dependency lines only. The Cargo.toml comment deliberately NAMES the
 * desktop-only crates it excludes, so a naive substring search over the whole
 * file matches the prose that documents their absence and reports the opposite
 * of the truth.
 */
const cargoDeps = readFileSync(resolve(APP, "src-tauri/Cargo.toml"), "utf8")
  .split("\n")
  .map((line) => line.split("#")[0].trim())
  .filter(Boolean)
  .join("\n");

/** `pnpm foo` -> the body of the `foo` script. */
function scriptBehind(command: string): string {
  const name = command.replace(/^(pnpm|npm run|yarn)\s+/, "").trim();
  const body = pkg.scripts[name];
  expect(body, `package.json has no "${name}" script`).toBeDefined();
  return body;
}

describe("mobile shell config", () => {
  it("builds the shared source with the Tauri flag set", () => {
    expect(scriptBehind(conf.build.beforeBuildCommand)).toContain("TAURI=1");
  });

  it("runs the dev server with the Tauri flag set", () => {
    // Without this the phone gets src/hooks.server (web Cognito) instead of
    // src/hooks.tauri.
    expect(scriptBehind(conf.build.beforeDevCommand)).toContain("TAURI=1");
  });

  it("serves the same static output the desktop host consumes", () => {
    expect(conf.build.frontendDist).toBe("../build");
  });

  it("keeps the identifier HQ already records for the Work app", () => {
    expect(conf.identifier).toBe("ai.indigo.hq-work");
  });

  it.each([
    "tray-icon",
    "window-vibrancy",
    "tauri-plugin-global-shortcut",
    "tauri-plugin-single-instance",
    "macos-private-api",
    "rfd",
  ])("does not depend on the desktop-only %s", (dep) => {
    // None of these build for iOS or Android.
    expect(cargoDeps).not.toContain(dep);
  });
});

/**
 * Icon sets are derivatives, not sources.
 *
 * `tauri ios init` seeds AppIcon.appiconset with Tauri's own placeholder logo,
 * and `tauri android init` does the same for the mipmap launcher icons. The
 * iOS placeholders were committed once and were indistinguishable in review
 * from real icons — the app would have shipped wearing the wrong logo. So the
 * generated bytes are gitignored on both platforms, and every mobile entry
 * point regenerates them from the single committed source image instead.
 *
 * The trade this makes: a fresh checkout has no AppIcon PNGs until `pnpm icons`
 * runs, so opening the Xcode project directly (rather than going through
 * `pnpm ios:build`) fails asset-catalog compilation until it does.
 */
const APPICON = "src-tauri/gen/apple/Assets.xcassets/AppIcon.appiconset";
const MIPMAP = "src-tauri/gen/android/app/src/main/res";

/** Repo-relative paths git tracks under `pathspec`, resolved from APP. */
function tracked(pathspec: string): string[] {
  return execFileSync("git", ["ls-files", "--", pathspec], {
    cwd: APP,
    encoding: "utf8",
  })
    .split("\n")
    .filter(Boolean);
}

describe("mobile icons are generated, not committed", () => {
  it.each([
    "ios:init",
    "ios:dev",
    "ios:build",
    "android:init",
    "android:dev",
    "android:build",
  ])("%s regenerates the icon set first", (name) => {
    expect(pkg.scripts[name], `package.json has no "${name}" script`).toMatch(
      /^pnpm icons &&/,
    );
  });

  it("keeps the `tauri` passthrough the Android Gradle build shells out to", () => {
    // gen/android's rustBuild task runs `npm run -- tauri android
    // android-studio-script`, so a missing script here fails the APK assembly
    // with only "Process 'command 'npm'' finished with non-zero exit value 1".
    // Nothing calls this script by hand, so nothing else would notice it going.
    expect(pkg.scripts.tauri).toBe("tauri");
  });

  it("generates from a source image that is actually in the repo", () => {
    const source = pkg.scripts.icons.replace(/^tauri icon\s+/, "").trim();
    expect(source, "icons script passes an explicit source").toBeTruthy();
    expect(
      existsSync(resolve(APP, source)),
      `icons source ${source} does not exist`,
    ).toBe(true);
  });

  it("tracks no AppIcon PNG", () => {
    // A tracked PNG here is a placeholder waiting to ship.
    expect(tracked(`${APPICON}/*.png`)).toEqual([]);
  });

  it("tracks no Android launcher PNG", () => {
    // `tauri android init` seeds these with the placeholder too.
    expect(tracked(`${MIPMAP}/mipmap-*/*.png`)).toEqual([]);
  });

  it("still tracks the asset-catalog manifest Xcode reads", () => {
    // Only the bytes are generated; the index that names them is source.
    expect(tracked(`${APPICON}/Contents.json`)).toHaveLength(1);
  });
});
