//! Tauri auto-updater nag — soft, user-initiated, channel-aware.
//!
//! Three channels (`util::release_channel::ReleaseChannel`):
//!   - Stable — every user. Polls the static
//!     `releases/latest/download/latest.json` alias that GitHub already
//!     filters to non-prereleases.
//!   - Beta   — `@getindigo.ai` users by default. Newer of (stable, beta).
//!   - Alpha  — `@getindigo.ai` opt-in via Settings. Newest of anything.
//!
//! Gating is layered:
//!   1. The Settings UI only renders the channel picker for
//!      `@getindigo.ai` users (`available_channels` command).
//!   2. The Rust-side resolver (`effective_channel`) coerces a non-indigo
//!      preference to Stable regardless of what's in `menubar.json` — a
//!      hand-edited config can't escape stable.
//!   3. The endpoint resolver falls back to the static stable alias on
//!      any GitHub API failure, so prerelease users behind a blocked
//!      proxy still get stable updates rather than nothing.
//!
//! This file replaces the older static-endpoint flow that called
//! `app.updater()` directly. The static endpoint in `tauri.conf.json` is
//! kept as the Stable channel URL — the `version_gate.rs` hard-yank path
//! continues to use it via `app.updater()` because hard-yank always pulls
//! the newest stable, regardless of channel preference.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
use std::time::Duration;

use chrono::{SecondsFormat, Utc};
use serde::Serialize;
use tauri::{AppHandle, Emitter, Manager};
use tauri_plugin_updater::UpdaterExt;
use url::Url;

use crate::commands::config::MenubarPrefs;
use crate::util::feature_gate;
use crate::util::logfile::log;
use crate::util::paths;
use crate::util::release_channel::{
    effective_channel, resolve_channel_endpoint, EndpointProvenance, ReleaseChannel,
    ResolvedChannelEndpoint,
};

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateInfo {
    pub version: String,
    pub body: Option<String>,
    pub date: Option<String>,
    /// Trusted local discovery time used to order the notification feed.
    ///
    /// This is intentionally generated by the app instead of copied from the
    /// release manifest. A repeated check for the same version preserves the
    /// first timestamp so an old update cannot jump back to the top of Inbox.
    pub detected_at: String,
}

/// Byte-progress for an in-flight desktop-app download. `percent` is omitted
/// when the updater did not report a total size.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateProgress {
    pub downloaded: u64,
    pub total: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub percent: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
struct UpdateInstallStarted<'a> {
    version: &'a str,
}

pub(crate) fn download_progress_percent(downloaded: u64, total: Option<u64>) -> Option<u32> {
    let total = total.filter(|size| *size > 0)?;
    Some(((downloaded.min(total) * 100) / total) as u32)
}

pub(crate) fn emit_update_download_progress(
    app: &AppHandle,
    downloaded: u64,
    total: Option<u64>,
) {
    let _ = app.emit(
        "update:progress",
        UpdateProgress {
            downloaded,
            total,
            percent: download_progress_percent(downloaded, total),
        },
    );
}

pub(crate) fn emit_update_install_started(app: &AppHandle, version: &str) {
    let _ = app.emit("update:install-started", UpdateInstallStarted { version });
}

/// Trusted updater state returned to the frontend.
///
/// `unchecked` covers startup before the first successful check and preserves
/// uncertainty after a failed check. `absent` is only written by a successful
/// latest check that confirms there is no update.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(tag = "status", content = "update", rename_all = "camelCase")]
pub enum PendingUpdateStatus {
    Unchecked,
    Absent,
    Pending(UpdateInfo),
}

impl PendingUpdateStatus {
    fn pending_info(&self) -> Option<UpdateInfo> {
        match self {
            Self::Pending(info) => Some(info.clone()),
            Self::Unchecked | Self::Absent => None,
        }
    }
}

#[derive(Debug)]
struct PendingUpdateLedger {
    status: PendingUpdateStatus,
    latest_check_id: u64,
}

impl Default for PendingUpdateLedger {
    fn default() -> Self {
        Self {
            status: PendingUpdateStatus::Unchecked,
            latest_check_id: 0,
        }
    }
}

/// Stores trusted updater state and orders overlapping updater checks.
pub struct PendingUpdate(Mutex<PendingUpdateLedger>);

impl Default for PendingUpdate {
    fn default() -> Self {
        Self(Mutex::new(PendingUpdateLedger::default()))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct UpdateCheckTicket(u64);

#[derive(Debug, Clone, PartialEq, Eq)]
struct PendingUpdateTransition {
    status: PendingUpdateStatus,
    applied: bool,
    announce_available: bool,
    cleared_pending: bool,
}

static UPDATE_INSTALL_IN_PROGRESS: AtomicBool = AtomicBool::new(false);
static UPDATE_CHECK_SERIALIZER: tokio::sync::Mutex<()> = tokio::sync::Mutex::const_new(());
const UPDATE_CHECK_INTERVAL: Duration = Duration::from_secs(21_600);
/// Betas iterate multiple times per day, so prerelease channels re-check every
/// 30 minutes while stable keeps the 6h cadence.
const PRERELEASE_UPDATE_CHECK_INTERVAL: Duration = Duration::from_secs(1_800);
const UPDATE_SYNC_RETRY_INTERVAL: Duration = Duration::from_secs(30);
pub(crate) const UPDATE_DEFERRED_DURING_SYNC: &str = "Update deferred while a sync is active";
pub(crate) const UPDATE_DEFERRED_DURING_MUTATION: &str =
    "Update deferred while an HQ change is active";
pub(crate) const UPDATE_DEFERRED_DURING_PROCESS_EXIT: &str =
    "Update deferred while HQ processes are still stopping";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum BackgroundUpdateAction {
    Install,
    DeferForSync,
    Announce,
}

fn install_failure_is_transient_deferral(error: &str) -> bool {
    matches!(
        error,
        UPDATE_DEFERRED_DURING_SYNC
            | UPDATE_DEFERRED_DURING_MUTATION
            | UPDATE_DEFERRED_DURING_PROCESS_EXIT
    )
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum UpdateAnnouncement {
    /// Keep the update in shared state and notify mounted app surfaces without
    /// creating a separate window.
    PersistentOnly,
    /// Also raise the compact banner/widget for users who deliberately opted
    /// out of automatic installation.
    TransientBanner,
}

fn should_raise_transient_update_surface(announcement: UpdateAnnouncement) -> bool {
    announcement == UpdateAnnouncement::TransientBanner
}

fn background_check_interval(channel: ReleaseChannel) -> Duration {
    match channel {
        ReleaseChannel::Stable => UPDATE_CHECK_INTERVAL,
        ReleaseChannel::Beta | ReleaseChannel::Alpha => PRERELEASE_UPDATE_CHECK_INTERVAL,
    }
}

fn background_update_action(
    automatic_updates: bool,
    sync_in_progress: bool,
    silent_install_supported: bool,
) -> BackgroundUpdateAction {
    match (
        automatic_updates && silent_install_supported,
        sync_in_progress,
    ) {
        (true, false) => BackgroundUpdateAction::Install,
        (true, true) => BackgroundUpdateAction::DeferForSync,
        (false, _) => BackgroundUpdateAction::Announce,
    }
}

/// Every supported desktop platform now has a safe silent-install path.
/// Windows uses `windows_update`: the minisign-verified package is staged, HQ
/// children are quiesced, and a copied signed helper waits for the parent to
/// exit before launching NSIS. This is deliberately a function rather than a
/// constant so platform policy remains explicit at each decision point.
pub(crate) fn silent_install_supported() -> bool {
    true
}

pub(crate) fn sync_in_progress() -> bool {
    crate::commands::process::is_registered("hq-sync")
        || hq_desktop_core::sync_progress::read_fresh_snapshot()
            .is_some_and(|snapshot| snapshot.status == "syncing")
}

/// Process-wide lease preventing separate app surfaces from starting the same
/// download concurrently. Dropping the lease resets the flag on every returning
/// path; a successful `app.restart()` terminates the process instead.
struct UpdateInstallGuard<'a> {
    in_progress: &'a AtomicBool,
}

impl<'a> UpdateInstallGuard<'a> {
    fn acquire(in_progress: &'a AtomicBool) -> Option<Self> {
        in_progress
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .ok()
            .map(|_| Self { in_progress })
    }
}

impl Drop for UpdateInstallGuard<'_> {
    fn drop(&mut self) {
        self.in_progress.store(false, Ordering::Release);
    }
}

fn detection_timestamp() -> String {
    Utc::now().to_rfc3339_opts(SecondsFormat::Millis, true)
}

fn discovered_update(version: String, body: Option<String>, date: Option<String>) -> UpdateInfo {
    UpdateInfo {
        version,
        body,
        date,
        detected_at: detection_timestamp(),
    }
}

fn begin_check(ledger: &mut PendingUpdateLedger) -> UpdateCheckTicket {
    ledger.latest_check_id = ledger.latest_check_id.wrapping_add(1);
    UpdateCheckTicket(ledger.latest_check_id)
}

fn preserved_transition(ledger: &PendingUpdateLedger) -> PendingUpdateTransition {
    PendingUpdateTransition {
        status: ledger.status.clone(),
        applied: false,
        announce_available: false,
        cleared_pending: false,
    }
}

/// Apply a discovered update only when it belongs to the latest-started check.
///
/// Metadata may change when an endpoint republishes the same version, but its
/// original discovery time and notification identity remain stable.
#[cfg(test)]
fn apply_discovered_update(
    ledger: &mut PendingUpdateLedger,
    ticket: UpdateCheckTicket,
    discovered: UpdateInfo,
) -> PendingUpdateTransition {
    apply_discovered_update_with_authority(ledger, ticket, discovered, true)
}

fn is_prerelease_version(version: &str) -> bool {
    let version = version.strip_prefix('v').unwrap_or(version);
    semver::Version::parse(version)
        .map(|version| !version.pre.is_empty())
        .unwrap_or(false)
}

fn apply_discovered_update_with_authority(
    ledger: &mut PendingUpdateLedger,
    ticket: UpdateCheckTicket,
    mut discovered: UpdateInfo,
    authoritative: bool,
) -> PendingUpdateTransition {
    if ticket.0 != ledger.latest_check_id {
        return preserved_transition(ledger);
    }

    // A prerelease-channel resolver fallback can still discover a stable
    // update, but it cannot prove that an already-known prerelease disappeared.
    if !authoritative
        && matches!(
            &ledger.status,
            PendingUpdateStatus::Pending(existing)
                if is_prerelease_version(&existing.version)
        )
        && !is_prerelease_version(&discovered.version)
    {
        return preserved_transition(ledger);
    }

    let announce_available = match &ledger.status {
        PendingUpdateStatus::Pending(existing) if existing.version == discovered.version => {
            discovered.detected_at.clone_from(&existing.detected_at);
            false
        }
        _ => true,
    };

    ledger.status = PendingUpdateStatus::Pending(discovered);
    PendingUpdateTransition {
        status: ledger.status.clone(),
        applied: true,
        announce_available,
        cleared_pending: false,
    }
}

/// Apply a confirmed no-update result only when it belongs to the latest check.
#[cfg(test)]
fn apply_confirmed_absent(
    ledger: &mut PendingUpdateLedger,
    ticket: UpdateCheckTicket,
) -> PendingUpdateTransition {
    apply_confirmed_absent_with_authority(ledger, ticket, true)
}

fn apply_confirmed_absent_with_authority(
    ledger: &mut PendingUpdateLedger,
    ticket: UpdateCheckTicket,
    authoritative: bool,
) -> PendingUpdateTransition {
    if ticket.0 != ledger.latest_check_id || !authoritative {
        return preserved_transition(ledger);
    }

    let cleared_pending = matches!(ledger.status, PendingUpdateStatus::Pending(_));
    ledger.status = PendingUpdateStatus::Absent;
    PendingUpdateTransition {
        status: ledger.status.clone(),
        applied: true,
        announce_available: false,
        cleared_pending,
    }
}

fn begin_app_check(app: &AppHandle) -> Result<UpdateCheckTicket, String> {
    let state = app
        .try_state::<PendingUpdate>()
        .ok_or_else(|| "updater state unavailable".to_string())?;
    let mut ledger = state.0.lock().unwrap_or_else(|e| e.into_inner());
    Ok(begin_check(&mut ledger))
}

fn apply_discovered_to_app(
    app: &AppHandle,
    ticket: UpdateCheckTicket,
    discovered: UpdateInfo,
    authoritative: bool,
) -> Result<PendingUpdateTransition, String> {
    let state = app
        .try_state::<PendingUpdate>()
        .ok_or_else(|| "updater state unavailable".to_string())?;
    let mut ledger = state.0.lock().unwrap_or_else(|e| e.into_inner());
    Ok(apply_discovered_update_with_authority(
        &mut ledger,
        ticket,
        discovered,
        authoritative,
    ))
}

fn apply_absent_to_app(
    app: &AppHandle,
    ticket: UpdateCheckTicket,
    authoritative: bool,
) -> Result<PendingUpdateTransition, String> {
    let state = app
        .try_state::<PendingUpdate>()
        .ok_or_else(|| "updater state unavailable".to_string())?;
    let mut ledger = state.0.lock().unwrap_or_else(|e| e.into_inner());
    Ok(apply_confirmed_absent_with_authority(
        &mut ledger,
        ticket,
        authoritative,
    ))
}

fn apply_absent_and_emit(
    app: &AppHandle,
    ticket: UpdateCheckTicket,
    authoritative: bool,
) -> Result<PendingUpdateStatus, String> {
    let transition = apply_absent_to_app(app, ticket, authoritative)?;
    if transition.applied && transition.cleared_pending {
        let _ = app.emit("update:cleared", ());
    }
    Ok(transition.status)
}

async fn record_and_announce_update(
    app: &AppHandle,
    ticket: UpdateCheckTicket,
    discovered: UpdateInfo,
    authoritative: bool,
    announcement: UpdateAnnouncement,
) -> Result<Option<UpdateInfo>, String> {
    let transition = apply_discovered_to_app(app, ticket, discovered, authoritative)?;
    let info = transition.status.pending_info();
    if !transition.applied || !transition.announce_available {
        return Ok(info);
    }

    let info = info.expect("an applied available transition always stores update info");
    let _ = app.emit("update:available", &info);
    // Only opted-out background discovery raises a transient surface. Manual
    // checks already have a visible caller, while automatic-install recovery
    // is represented persistently in Settings, the version popout, and Inbox.
    // Opening a separate banner for either case makes the desktop look like
    // windows are flashing while the user is already working in it.
    // US-003: widget takeover must never fall back to native banners.
    if should_raise_transient_update_surface(announcement)
        && (crate::commands::banner::custom_banner_enabled()
            || crate::commands::widget::takeover_active(app))
    {
        let _ = crate::commands::banner::show_update_banner(
            app.clone(),
            info.version.clone(),
            info.body.clone(),
        )
        .await;
    }

    Ok(Some(info))
}

/// Read the user's stored channel preference from `~/.hq/menubar.json`,
/// or `None` if the file is missing / unparseable / the field is absent.
/// We deliberately do NOT propagate errors — a corrupted menubar.json
/// must never break the updater. The caller treats `None` as "no
/// preference" and lets `effective_channel` apply identity-aware
/// defaults.
fn read_stored_release_channel() -> Option<String> {
    let path = paths::menubar_json_path().ok()?;
    let contents = std::fs::read_to_string(&path).ok()?;
    let prefs: MenubarPrefs = serde_json::from_str(&contents).ok()?;
    prefs.release_channel
}

/// Resolve the per-channel updater endpoint URL the background loop and
/// on-demand command should poll. Combines the stored preference with
/// the indigo gate, then resolves to a `latest.json` URL via the
/// `release_channel` module.
async fn resolve_endpoint() -> (ReleaseChannel, ResolvedChannelEndpoint) {
    let stored = read_stored_release_channel();
    let is_indigo = feature_gate::is_indigo_user().await;
    let channel: ReleaseChannel = effective_channel(stored.as_deref(), is_indigo);
    let resolved = resolve_channel_endpoint(channel).await;
    log(
        "updater",
        &format!(
            "resolved channel={} endpoint={} provenance={:?}",
            channel.as_str(),
            resolved.url,
            resolved.provenance
        ),
    );
    (channel, resolved)
}

struct ChannelAwareUpdater {
    updater: tauri_plugin_updater::Updater,
    provenance: EndpointProvenance,
    channel: ReleaseChannel,
}

/// Build a channel-aware `tauri_plugin_updater::Updater` for this
/// invocation. Tauri's `app.updater()` always uses the static endpoint
/// from `tauri.conf.json`; `app.updater_builder()` lets us override
/// per-call so the same binary serves three channels without rebuild.
async fn channel_aware_updater(app: &AppHandle) -> Result<ChannelAwareUpdater, String> {
    let (channel, resolved) = resolve_endpoint().await;
    let endpoint =
        Url::parse(&resolved.url).map_err(|e| format!("invalid updater endpoint: {e}"))?;
    let updater = app
        .updater_builder()
        .endpoints(vec![endpoint])
        .map_err(|e| format!("updater_builder.endpoints: {e}"))?
        .build()
        .map_err(|e| format!("updater_builder.build: {e}"))?;
    Ok(ChannelAwareUpdater {
        updater,
        provenance: resolved.provenance,
        channel,
    })
}

#[tauri::command]
pub async fn check_for_updates(app: AppHandle) -> Result<Option<UpdateInfo>, String> {
    let _check_guard = UPDATE_CHECK_SERIALIZER.lock().await;
    let ticket = begin_app_check(&app)?;
    let updater = channel_aware_updater(&app).await?;
    let authoritative = updater.provenance.absence_is_authoritative();
    match updater.updater.check().await {
        Ok(Some(update)) => {
            let info = discovered_update(
                update.version.clone(),
                update.body.clone(),
                update.date.map(|d| d.to_string()),
            );
            record_and_announce_update(
                &app,
                ticket,
                info,
                authoritative,
                UpdateAnnouncement::PersistentOnly,
            )
            .await
        }
        Ok(None) => {
            // Up to date — clear any previously stored pending update so a
            // pulled/superseded release doesn't keep hydrating surfaces
            // (e.g. the version pop-out) as "Update available" forever.
            Ok(apply_absent_and_emit(&app, ticket, authoritative)?.pending_info())
        }
        Err(e) => Err(e.to_string()),
    }
}

/// Return the update the background checker (or a manual check) already
/// found, if any. Lets late-mounting surfaces — e.g. the status-bar version
/// pop-out (US-017) — hydrate "update available" state without waiting for
/// the next `update:available` event or forcing a fresh network check.
#[tauri::command]
pub fn get_pending_update(app: AppHandle) -> PendingUpdateStatus {
    app.try_state::<PendingUpdate>()
        .map(|state| {
            state
                .0
                .lock()
                .unwrap_or_else(|e| e.into_inner())
                .status
                .clone()
        })
        .unwrap_or(PendingUpdateStatus::Unchecked)
}

async fn install_verified_update(
    app: &AppHandle,
    update: &tauri_plugin_updater::Update,
) -> Result<(), String> {
    emit_update_install_started(app, &update.version);
    #[cfg(target_os = "windows")]
    {
        crate::windows_update::install_verified_update(app, update).await
    }
    #[cfg(not(target_os = "windows"))]
    {
        let mut downloaded = 0_u64;
        update
            .download_and_install(
                |chunk, total| {
                    downloaded = downloaded.saturating_add(chunk as u64);
                    emit_update_download_progress(app, downloaded, total);
                },
                || {},
            )
            .await
            .map_err(|error| error.to_string())?;
        crate::commands::hq_work::spawn_maybe_co_install_hq_work();
        app.restart();
    }
}

/// Install the newest stable release through the same single-flight and
/// platform-safe lifecycle as the normal updater. The hard version gate uses
/// this entry point so it cannot drift back to Tauri's abrupt Windows exit.
pub(crate) async fn install_stable_update(app: &AppHandle) -> Result<(), String> {
    let _install_guard = UpdateInstallGuard::acquire(&UPDATE_INSTALL_IN_PROGRESS)
        .ok_or_else(|| "An update installation is already in progress".to_string())?;
    let _check_guard = UPDATE_CHECK_SERIALIZER.lock().await;
    let updater = app.updater().map_err(|error| error.to_string())?;
    match updater.check().await {
        Ok(Some(update)) => install_verified_update(app, &update).await,
        Ok(None) => Err(
            "hq-pro hard-gate fired but tauri-updater sees no release; latest.json may be stale"
                .to_string(),
        ),
        Err(error) => Err(error.to_string()),
    }
}

#[tauri::command]
pub async fn install_update(app: AppHandle) -> Result<(), String> {
    let _install_guard = UpdateInstallGuard::acquire(&UPDATE_INSTALL_IN_PROGRESS)
        .ok_or_else(|| "An update installation is already in progress".to_string())?;
    let _check_guard = UPDATE_CHECK_SERIALIZER.lock().await;
    let ticket = begin_app_check(&app)?;

    // Note: We must call updater.check() again here because the tauri_plugin_updater::Update
    // type cannot be stored (not Clone). The PendingUpdate state only holds metadata (UpdateInfo).
    // This is an architectural constraint of the plugin, not a redundant call.
    //
    // We re-resolve the channel endpoint at install time too — if the user
    // changes their channel preference between "Check Now" and "Install",
    // we honor the latest choice. The endpoint resolution is cheap (the
    // GH API result is uncached but the next 6h check will hit it again
    // anyway) and the stable fallback path skips the network entirely.
    let updater = channel_aware_updater(&app).await?;
    let authoritative = updater.provenance.absence_is_authoritative();
    match updater.updater.check().await {
        Ok(Some(update)) => {
            let info = discovered_update(
                update.version.clone(),
                update.body.clone(),
                update.date.map(|d| d.to_string()),
            );
            let _ = record_and_announce_update(
                &app,
                ticket,
                info,
                authoritative,
                UpdateAnnouncement::PersistentOnly,
            )
            .await?;
            // Best-effort HQ Work co-install on platforms where it cannot race
            // the NSIS file swap. Windows performs only the desktop update in
            // this critical section.
            #[cfg(not(target_os = "windows"))]
            crate::commands::hq_work::spawn_maybe_co_install_hq_work();
            install_verified_update(&app, &update).await
        }
        Ok(None) => {
            let _ = apply_absent_and_emit(&app, ticket, authoritative)?;
            Err("No update available".to_string())
        }
        Err(e) => Err(e.to_string()),
    }
}

/// Tauri command returning the list of channels the user is allowed to
/// pick from. `@getindigo.ai` users see all three (stable / beta /
/// alpha); everyone else sees only stable, which makes the picker
/// degenerate into a non-interactive label — the Svelte side keys off
/// `length > 1` to decide whether to render it.
///
/// Returned in display order: stable → beta → alpha (most stable first).
#[tauri::command]
pub async fn available_channels() -> Vec<String> {
    if feature_gate::is_indigo_user().await {
        vec![
            ReleaseChannel::Stable.as_str().to_string(),
            ReleaseChannel::Beta.as_str().to_string(),
            ReleaseChannel::Alpha.as_str().to_string(),
        ]
    } else {
        vec![ReleaseChannel::Stable.as_str().to_string()]
    }
}

/// Tauri command returning `true` iff the signed-in user's email ends in
/// `@getindigo.ai`. The canonical frontend-facing handle on the
/// `@getindigo.ai` predicate — delegates straight to
/// `feature_gate::is_indigo_user`.
///
/// Settings uses it to gate the Updates-group **staging channel** toggle, a
/// builder-only control that points the in-app Update pill at
/// `hq-core-staging`. It must NOT be confused with `meetings_feature_enabled`
/// / `desktop_features_enabled`, which graduated to a GA gate (any signed-in
/// user) when the Meetings + desktop window left the Indigo dogfood. Wiring
/// the staging toggle to that GA gate exposed it to every signed-in user; this
/// command keeps it `@getindigo.ai`-only — matching the defense-in-depth email
/// gate the staging backend (`commands/hq_core_staging.rs`) already applies, so
/// a non-Indigo user can neither see nor action the control.
#[tauri::command]
pub async fn is_indigo_user() -> bool {
    feature_gate::is_indigo_user().await
}

/// Spawns a background task that checks for updates on launch (after 10s delay)
/// and every 6 hours thereafter.
///
/// Automatic updates are installed natively here instead of depending on a
/// particular WebView to receive `update:available`. That frontend-owned
/// handshake was lossy: users whose hidden popover had not mounted (or missed
/// the event) were left with an unexpected manual Install prompt. An active sync
/// defers the attempt for 30 seconds; an install failure falls back to the
/// ordinary update notification so the user still has a recovery path.
/// Menu-item id for the macOS app-menu "Check for Updates…" entry.
#[cfg(target_os = "macos")]
pub const MENU_CHECK_FOR_UPDATES_ID: &str = "app-menu:check-for-updates";

/// Build the macOS application menu with a "Check for Updates…" item under
/// About, keeping the standard app/Edit/Window entries (the app previously
/// ran on Tauri's implicit default menu). The item drives the exact same
/// `check_for_updates` command the Settings → Updates pane and the background
/// checker use — no separate update logic. On "update found" the command's own
/// `update:available` event drives the existing update UI; on "up to date" we
/// surface a native notification with the current version.
#[cfg(target_os = "macos")]
pub fn setup_app_menu(app: &tauri::App) -> tauri::Result<()> {
    use tauri::menu::{AboutMetadata, MenuBuilder, MenuItemBuilder, SubmenuBuilder};

    let check_item = MenuItemBuilder::with_id(MENU_CHECK_FOR_UPDATES_ID, "Check for Updates…")
        .build(app)?;
    let app_menu = SubmenuBuilder::new(app, "HQ")
        .about(Some(AboutMetadata::default()))
        .separator()
        .item(&check_item)
        .separator()
        .services()
        .separator()
        .hide()
        .hide_others()
        .show_all()
        .separator()
        .quit()
        .build()?;
    // Standard Edit/Window menus so text fields and window shortcuts keep
    // working once the implicit default menu is replaced.
    let edit_menu = SubmenuBuilder::new(app, "Edit")
        .undo()
        .redo()
        .separator()
        .cut()
        .copy()
        .paste()
        .select_all()
        .build()?;
    let window_menu = SubmenuBuilder::new(app, "Window")
        .minimize()
        .maximize()
        .separator()
        .close_window()
        .build()?;
    let menu = MenuBuilder::new(app)
        .items(&[&app_menu, &edit_menu, &window_menu])
        .build()?;
    app.set_menu(menu)?;

    app.on_menu_event(|handle, event| {
        if event.id().as_ref() != MENU_CHECK_FOR_UPDATES_ID {
            return;
        }
        let handle = handle.clone();
        tauri::async_runtime::spawn(async move {
            match check_for_updates(handle.clone()).await {
                // Update found: `check_for_updates` already emitted
                // `update:available`, which every existing surface (Settings
                // row, banner, version pop-out) listens for.
                Ok(Some(_)) => {}
                Ok(None) => notify_manual_check(&handle, &up_to_date_body(&handle)),
                Err(e) => {
                    log("updater", &format!("menu check_for_updates failed: {e}"));
                    notify_manual_check(&handle, "Couldn\u{2019}t check for updates. Try again later.");
                }
            }
        });
    });
    Ok(())
}

#[cfg(target_os = "macos")]
fn up_to_date_body(app: &AppHandle) -> String {
    format!(
        "You\u{2019}re up to date \u{2014} v{}",
        app.package_info().version
    )
}

/// Native confirmation for a user-initiated menu check. Notification (not a
/// modal) so it works whether or not any app window is frontmost.
#[cfg(target_os = "macos")]
fn notify_manual_check(app: &AppHandle, body: &str) {
    use tauri_plugin_notification::NotificationExt;
    if let Err(e) = app
        .notification()
        .builder()
        .title("HQ")
        .body(body)
        .show()
    {
        log("updater", &format!("manual update-check notification failed: {e}"));
    }
}

pub fn setup_update_checker(app: &AppHandle) {
    let handle = app.clone();
    tauri::async_runtime::spawn(async move {
        // Wait 10 seconds for app to settle
        tokio::time::sleep(Duration::from_secs(10)).await;

        loop {
            let mut next_check = UPDATE_CHECK_INTERVAL;
            {
                let _check_guard = UPDATE_CHECK_SERIALIZER.lock().await;
                let ticket = begin_app_check(&handle);
                // Check for updates silently — log errors for field debugging via Console.app
                match ticket {
                    Ok(ticket) => match channel_aware_updater(&handle).await {
                        Ok(updater) => {
                            let authoritative = updater.provenance.absence_is_authoritative();
                            next_check = background_check_interval(updater.channel);
                            match updater.updater.check().await {
                                Ok(Some(update)) => {
                                    let info = discovered_update(
                                        update.version.clone(),
                                        update.body.clone(),
                                        update.date.map(|d| d.to_string()),
                                    );
                                    match background_update_action(
                                        hq_desktop_core::hq_cli_update::auto_update_enabled(),
                                        sync_in_progress(),
                                        silent_install_supported(),
                                    ) {
                                        BackgroundUpdateAction::Install => {
                                            match UpdateInstallGuard::acquire(
                                                &UPDATE_INSTALL_IN_PROGRESS,
                                            ) {
                                                Some(_install_guard) => {
                                                    log(
                                                        "updater",
                                                        &format!(
                                                            "automatic update enabled — installing {}",
                                                            info.version
                                                        ),
                                                    );
                                                    #[cfg(not(target_os = "windows"))]
                                                    crate::commands::hq_work::spawn_maybe_co_install_hq_work();
                                                    match install_verified_update(&handle, &update)
                                                        .await
                                                    {
                                                        Ok(()) => {
                                                            log(
                                                                "updater",
                                                                "automatic update handed off successfully",
                                                            );
                                                        }
                                                        Err(error)
                                                            if install_failure_is_transient_deferral(
                                                                &error,
                                                            ) =>
                                                        {
                                                            log(
                                                                "updater",
                                                                "automatic update deferred during install startup; retrying soon",
                                                            );
                                                            next_check =
                                                                UPDATE_SYNC_RETRY_INTERVAL;
                                                        }
                                                        Err(error) => {
                                                            log(
                                                                "updater",
                                                                &format!(
                                                                    "automatic install failed — offering manual recovery: {error}"
                                                                ),
                                                            );
                                                            if let Err(record_error) =
                                                                record_and_announce_update(
                                                                    &handle,
                                                                    ticket,
                                                                    info,
                                                                    authoritative,
                                                                    UpdateAnnouncement::PersistentOnly,
                                                                )
                                                                .await
                                                            {
                                                                eprintln!(
                                                                    "[updater] failed to store background update: {record_error}"
                                                                );
                                                            }
                                                        }
                                                    }
                                                }
                                                None => {
                                                    log(
                                                        "updater",
                                                        "automatic install already in progress — retrying soon",
                                                    );
                                                    next_check = UPDATE_SYNC_RETRY_INTERVAL;
                                                }
                                            }
                                        }
                                        BackgroundUpdateAction::DeferForSync => {
                                            log(
                                                "updater",
                                                "automatic update deferred while sync is active",
                                            );
                                            next_check = UPDATE_SYNC_RETRY_INTERVAL;
                                        }
                                        BackgroundUpdateAction::Announce => {
                                            if let Err(e) = record_and_announce_update(
                                                &handle,
                                                ticket,
                                                info,
                                                authoritative,
                                                UpdateAnnouncement::TransientBanner,
                                            )
                                            .await
                                            {
                                                eprintln!(
                                                    "[updater] failed to store background update: {e}"
                                                );
                                            }
                                        }
                                    }
                                }
                                Ok(None) => {
                                    log(
                                        "updater",
                                        &format!(
                                            "background check: up to date (current v{})",
                                            handle.package_info().version
                                        ),
                                    );
                                    if let Err(e) =
                                        apply_absent_and_emit(&handle, ticket, authoritative)
                                    {
                                        eprintln!(
                                            "[updater] failed to store no-update result: {e}"
                                        );
                                    }
                                }
                                Err(e) => {
                                    eprintln!("[updater] background check failed: {e}");
                                    log("updater", &format!("background check failed: {e}"));
                                }
                            }
                        }
                        Err(e) => {
                            eprintln!("[updater] failed to build channel-aware updater: {e}")
                        }
                    },
                    Err(e) => eprintln!("[updater] failed to start background check: {e}"),
                }
            }
            tokio::time::sleep(next_check).await;
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;

    fn update(version: &str, body: &str, detected_at: &str) -> UpdateInfo {
        UpdateInfo {
            version: version.to_string(),
            body: Some(body.to_string()),
            date: Some("2026-07-27T15:00:00Z".to_string()),
            detected_at: detected_at.to_string(),
        }
    }

    #[test]
    fn update_info_serializes_camel_case_with_trusted_iso_detection_time() {
        let info = discovered_update("0.10.36".to_string(), None, None);
        assert!(chrono::DateTime::parse_from_rfc3339(&info.detected_at).is_ok());

        let json = serde_json::to_value(&info).expect("UpdateInfo should serialize");
        assert_eq!(json["detectedAt"], info.detected_at);
        assert!(json.get("detected_at").is_none());
    }

    #[test]
    fn repeated_version_preserves_first_detection_and_is_not_a_new_transition() {
        let mut ledger = PendingUpdateLedger::default();
        let first_detected_at = "2026-07-27T15:00:00.000Z";
        let first_ticket = begin_check(&mut ledger);
        let first = apply_discovered_update(
            &mut ledger,
            first_ticket,
            update("0.10.36", "Original notes", first_detected_at),
        );
        assert!(first.applied);
        assert!(first.announce_available);

        let repeat_ticket = begin_check(&mut ledger);
        let repeated = apply_discovered_update(
            &mut ledger,
            repeat_ticket,
            update("0.10.36", "Republished notes", "2026-07-27T16:00:00.000Z"),
        );

        assert!(repeated.applied);
        assert!(!repeated.announce_available);
        let returned = repeated.status.pending_info().expect("pending update");
        assert_eq!(returned.detected_at, first_detected_at);
        assert_eq!(returned.body.as_deref(), Some("Republished notes"));
        assert_eq!(ledger.status, repeated.status);
    }

    #[test]
    fn different_version_is_a_new_transition_with_its_own_detection_time() {
        let mut ledger = PendingUpdateLedger {
            status: PendingUpdateStatus::Pending(update(
                "0.10.36",
                "Old update",
                "2026-07-27T15:00:00.000Z",
            )),
            latest_check_id: 0,
        };
        let next_detected_at = "2026-07-27T17:00:00.000Z";

        let ticket = begin_check(&mut ledger);
        let transition = apply_discovered_update(
            &mut ledger,
            ticket,
            update("0.10.37", "New update", next_detected_at),
        );

        assert!(transition.applied);
        assert!(transition.announce_available);
        let returned = transition.status.pending_info().expect("pending update");
        assert_eq!(returned.detected_at, next_detected_at);
        assert_eq!(ledger.status, transition.status);
    }

    #[test]
    fn clearing_reports_only_the_actual_some_to_none_transition() {
        let mut ledger = PendingUpdateLedger {
            status: PendingUpdateStatus::Pending(update(
                "0.10.36",
                "Pending update",
                "2026-07-27T15:00:00.000Z",
            )),
            latest_check_id: 0,
        };

        let first_ticket = begin_check(&mut ledger);
        let first = apply_confirmed_absent(&mut ledger, first_ticket);
        assert!(first.applied);
        assert!(first.cleared_pending);
        assert_eq!(ledger.status, PendingUpdateStatus::Absent);

        let second_ticket = begin_check(&mut ledger);
        let second = apply_confirmed_absent(&mut ledger, second_ticket);
        assert!(second.applied);
        assert!(!second.cleared_pending);
    }

    #[test]
    fn download_progress_percent_is_none_without_a_total_and_caps_at_100() {
        assert_eq!(download_progress_percent(42, None), None);
        assert_eq!(download_progress_percent(42, Some(0)), None);
        assert_eq!(download_progress_percent(42, Some(100)), Some(42));
        assert_eq!(download_progress_percent(100, Some(100)), Some(100));
        assert_eq!(download_progress_percent(150, Some(100)), Some(100));
    }

    #[test]
    fn install_guard_is_single_flight_and_resets_when_dropped() {
        let in_progress = AtomicBool::new(false);
        let first = UpdateInstallGuard::acquire(&in_progress).expect("first install acquires");

        assert!(UpdateInstallGuard::acquire(&in_progress).is_none());
        drop(first);

        assert!(UpdateInstallGuard::acquire(&in_progress).is_some());
    }

    #[test]
    fn background_check_interval_is_shorter_for_prerelease_channels() {
        assert_eq!(
            background_check_interval(ReleaseChannel::Stable),
            Duration::from_secs(21_600)
        );
        assert_eq!(
            background_check_interval(ReleaseChannel::Beta),
            Duration::from_secs(1_800)
        );
        assert_eq!(
            background_check_interval(ReleaseChannel::Alpha),
            Duration::from_secs(1_800)
        );
    }

    #[test]
    fn automatic_background_updates_install_without_announcing() {
        assert_eq!(
            background_update_action(true, false, true),
            BackgroundUpdateAction::Install
        );
    }

    #[test]
    fn automatic_background_updates_defer_during_sync() {
        assert_eq!(
            background_update_action(true, true, true),
            BackgroundUpdateAction::DeferForSync
        );
        assert_eq!(UPDATE_SYNC_RETRY_INTERVAL, Duration::from_secs(30));
        assert!(install_failure_is_transient_deferral(
            UPDATE_DEFERRED_DURING_SYNC
        ));
        assert!(install_failure_is_transient_deferral(
            UPDATE_DEFERRED_DURING_MUTATION
        ));
        assert!(install_failure_is_transient_deferral(
            UPDATE_DEFERRED_DURING_PROCESS_EXIT
        ));
        assert!(!install_failure_is_transient_deferral(
            "Windows update helper did not become ready"
        ));
    }

    #[test]
    fn opted_out_background_updates_keep_the_manual_notification() {
        assert_eq!(
            background_update_action(false, false, true),
            BackgroundUpdateAction::Announce
        );
        assert_eq!(
            background_update_action(false, true, true),
            BackgroundUpdateAction::Announce
        );
    }

    /// Regression: 2026-08-02 Windows field failure. Silent background installs
    /// on a platform that cannot swap locked files must announce instead —
    /// even mid-sync, the announce path wins over a deferred install.
    #[test]
    fn platforms_without_silent_install_always_announce() {
        assert_eq!(
            background_update_action(true, false, false),
            BackgroundUpdateAction::Announce
        );
        assert_eq!(
            background_update_action(true, true, false),
            BackgroundUpdateAction::Announce
        );
        assert_eq!(
            background_update_action(false, false, false),
            BackgroundUpdateAction::Announce
        );
    }

    #[test]
    fn every_platform_has_a_safe_silent_install_path() {
        assert!(silent_install_supported());
    }

    #[test]
    fn persistent_update_announcements_never_open_a_transient_window() {
        assert!(!should_raise_transient_update_surface(
            UpdateAnnouncement::PersistentOnly
        ));
        assert!(should_raise_transient_update_surface(
            UpdateAnnouncement::TransientBanner
        ));
    }

    #[test]
    fn initial_state_is_trusted_unchecked_wire_state() {
        let ledger = PendingUpdateLedger::default();
        assert_eq!(ledger.status, PendingUpdateStatus::Unchecked);
        assert_eq!(
            serde_json::to_value(&ledger.status).expect("status should serialize"),
            serde_json::json!({ "status": "unchecked" })
        );
    }

    #[test]
    fn pending_and_absent_wire_states_are_discriminated() {
        let pending = PendingUpdateStatus::Pending(update(
            "0.10.36",
            "Pending update",
            "2026-07-27T15:00:00.000Z",
        ));
        let pending_json = serde_json::to_value(&pending).expect("pending should serialize");
        assert_eq!(pending_json["status"], "pending");
        assert_eq!(pending_json["update"]["version"], "0.10.36");
        assert_eq!(
            serde_json::to_value(PendingUpdateStatus::Absent).expect("absent should serialize"),
            serde_json::json!({ "status": "absent" })
        );
    }

    #[test]
    fn older_available_result_cannot_overwrite_newer_confirmed_absence() {
        let mut ledger = PendingUpdateLedger::default();
        let older = begin_check(&mut ledger);
        let newer = begin_check(&mut ledger);

        let absent = apply_confirmed_absent(&mut ledger, newer);
        assert!(absent.applied);
        assert_eq!(ledger.status, PendingUpdateStatus::Absent);

        let stale = apply_discovered_update(
            &mut ledger,
            older,
            update("0.10.36", "Stale update", "2026-07-27T15:00:00.000Z"),
        );
        assert!(!stale.applied);
        assert!(!stale.announce_available);
        assert_eq!(ledger.status, PendingUpdateStatus::Absent);
    }

    #[test]
    fn older_absent_result_cannot_clear_newer_pending_update() {
        let mut ledger = PendingUpdateLedger::default();
        let older = begin_check(&mut ledger);
        let newer = begin_check(&mut ledger);

        let available = apply_discovered_update(
            &mut ledger,
            newer,
            update("0.10.37", "Newest update", "2026-07-27T16:00:00.000Z"),
        );
        assert!(available.applied);

        let stale = apply_confirmed_absent(&mut ledger, older);
        assert!(!stale.applied);
        assert!(!stale.cleared_pending);
        assert_eq!(ledger.status, available.status);
    }

    #[test]
    fn failed_check_preserves_the_prior_trusted_state() {
        let pending = PendingUpdateStatus::Pending(update(
            "0.10.36",
            "Known update",
            "2026-07-27T15:00:00.000Z",
        ));
        let mut ledger = PendingUpdateLedger {
            status: pending.clone(),
            latest_check_id: 0,
        };

        let _failed_check = begin_check(&mut ledger);
        // A failed endpoint/check never invokes an apply helper.
        assert_eq!(ledger.status, pending);
    }

    #[test]
    fn non_authoritative_fallback_absence_preserves_pending_prerelease() {
        let pending = PendingUpdateStatus::Pending(update(
            "0.10.36-beta.1",
            "Known beta",
            "2026-07-27T15:00:00.000Z",
        ));
        let mut ledger = PendingUpdateLedger {
            status: pending.clone(),
            latest_check_id: 0,
        };
        let ticket = begin_check(&mut ledger);

        let transition = apply_confirmed_absent_with_authority(&mut ledger, ticket, false);

        assert!(!transition.applied);
        assert!(!transition.cleared_pending);
        assert_eq!(ledger.status, pending);
    }

    #[test]
    fn non_authoritative_stable_fallback_cannot_replace_pending_prerelease() {
        let pending = PendingUpdateStatus::Pending(update(
            "0.10.36-beta.1",
            "Known beta",
            "2026-07-27T15:00:00.000Z",
        ));
        let mut ledger = PendingUpdateLedger {
            status: pending.clone(),
            latest_check_id: 0,
        };
        let ticket = begin_check(&mut ledger);

        let transition = apply_discovered_update_with_authority(
            &mut ledger,
            ticket,
            update("0.10.36", "Fallback stable", "2026-07-27T16:00:00.000Z"),
            false,
        );

        assert!(!transition.applied);
        assert!(!transition.announce_available);
        assert_eq!(ledger.status, pending);
    }
}
