; HQ installer hooks — Windows (NSIS).
!include "StrFunc.nsh"
${StrStr}
${StrLen}

!macro HQ_CAPTURE_DOWNLOAD_TOKEN
  ; Capture only this setup executable's own download URL. The marker is
  ; generated by the default-off marketing gate and contains no user identity.
  Delete "$PROFILE\.hq\download-token"
  ReadINIStr $0 "$EXEPATH:Zone.Identifier" "ZoneTransfer" "HostUrl"
  ${StrStr} $1 $0 "https://github.com/indigoai-us/hq-desktop-app/releases/latest/download/HQ_x64-setup.exe?downloadToken="
  ${If} $1 == $0
    StrCpy $2 $0 102
    ${If} $2 == "https://github.com/indigoai-us/hq-desktop-app/releases/latest/download/HQ_x64-setup.exe?downloadToken="
      StrCpy $3 $0 43 102
      ${StrLen} $4 $0
      ${If} $4 == 145
        CreateDirectory "$PROFILE\.hq"
        FileOpen $5 "$PROFILE\.hq\download-token" w
        FileWrite $5 "$3"
        FileClose $5
      ${EndIf}
    ${EndIf}
  ${Else}
    ${StrStr} $1 $0 "https://github.com/indigoai-us/hq-desktop-app/releases/latest/download/HQ_arm64-setup.exe?downloadToken="
    ${If} $1 == $0
      StrCpy $2 $0 104
      ${If} $2 == "https://github.com/indigoai-us/hq-desktop-app/releases/latest/download/HQ_arm64-setup.exe?downloadToken="
        StrCpy $3 $0 43 104
        ${StrLen} $4 $0
        ${If} $4 == 147
          CreateDirectory "$PROFILE\.hq"
          FileOpen $5 "$PROFILE\.hq\download-token" w
          FileWrite $5 "$3"
          FileClose $5
        ${EndIf}
      ${EndIf}
    ${EndIf}
  ${EndIf}
!macroend
;
; Field failure 2026-08-02: a background update ran this installer while
; hq-sync-menubar.exe and processes spawned from the install directory were
; still running. NSIS cannot overwrite open files, so the install died
; mid-copy ("Error opening file for writing: …\hq-sync-menubar.exe"), leaving
; a half-removed app whose uninstaller was also broken. These hooks stop every
; HQ process running from $INSTDIR before any file is touched — on install
; AND uninstall — so a fresh setup self-heals over that corrupted state.
;
; Scope discipline: never kill by generic image name (a bare node.exe kill
; would take out unrelated user processes). The PowerShell sweep matches on
; ExecutablePath under $INSTDIR only; the taskkill fast paths name
; HQ-unique executables.

!macro HQ_STOP_INSTALL_DIR_PROCESSES
  DetailPrint "Stopping running HQ processes"
  ; No /T on the app kill: when the in-app updater launches this installer,
  ; the installer IS a descendant of hq-sync-menubar.exe — a tree kill would
  ; terminate the running installer itself. Children that matter are caught
  ; by the $INSTDIR-scoped sweep below.
  nsExec::ExecToLog 'taskkill /F /IM "hq-sync-menubar.exe"'
  Pop $0
  nsExec::ExecToLog 'taskkill /F /T /IM "recall-desktop-sdk.exe"'
  Pop $0
  nsExec::ExecToLog 'powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Get-CimInstance Win32_Process | Where-Object { $$null -ne $$_.ExecutablePath -and $$_.ExecutablePath -like \"$INSTDIR\*\" } | ForEach-Object { Stop-Process -Id $$_.ProcessId -Force -ErrorAction SilentlyContinue }"'
  Pop $0
  Sleep 1000
!macroend

; The UI ships as bundle resources under $INSTDIR\ui with content-hashed file
; names that change every release. NSIS overwrites files but never removes the
; previous release's assets, and the generated uninstaller deletes only the
; files of its own build, so after an upgrade the old assets would pile up in
; ui\ and keep $INSTDIR alive after uninstall. The tree belongs entirely to the
; bundle: clear it before every install and before uninstall.
!macro HQ_REMOVE_BUNDLED_UI
  ${If} $INSTDIR != ""
    RMDir /r "$INSTDIR\ui"
  ${EndIf}
!macroend

!macro NSIS_HOOK_PREINSTALL
  !insertmacro HQ_CAPTURE_DOWNLOAD_TOKEN
  !insertmacro HQ_STOP_INSTALL_DIR_PROCESSES
  !insertmacro HQ_REMOVE_BUNDLED_UI
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  !insertmacro HQ_STOP_INSTALL_DIR_PROCESSES
  !insertmacro HQ_REMOVE_BUNDLED_UI
!macroend
