//! Pure drift-scope path and hash helpers shared by the desktop app.

use std::collections::BTreeMap;
use std::path::Path;

use sha1::{Digest, Sha1};

/// Read `rules.locked` from the user's local `core.yaml`. Returns an empty
/// vec if the file is missing/unparseable — same fail-quiet posture as
/// `get_local_version` (don't pester users without a working HQ).
///
/// Returns relative paths exactly as they appear in `core.yaml` (e.g.
/// `.claude/CLAUDE.md`, `core/policies/`). Trailing-slash convention
/// indicates "this directory and everything under it"; leaf paths are
/// single-file scopes.
pub fn read_locked_paths(hq_folder: &Path) -> Vec<String> {
    let canonical = hq_folder.join("core").join("core.yaml");
    let legacy = hq_folder.join("core.yaml");
    let core_yaml = if canonical.is_file() {
        canonical
    } else {
        legacy
    };
    let Ok(bytes) = std::fs::read(&core_yaml) else {
        return Vec::new();
    };
    let Ok(parsed) = serde_yaml::from_slice::<serde_yaml::Value>(&bytes) else {
        return Vec::new();
    };
    let Some(locked) = parsed.get("rules").and_then(|r| r.get("locked")) else {
        return Vec::new();
    };
    let Some(arr) = locked.as_sequence() else {
        return Vec::new();
    };
    arr.iter()
        .filter_map(|v| v.as_str().map(|s| s.to_string()))
        .collect()
}

/// Paths excluded from drift detection (both release and staging).
///
/// Hardcoded in the app rather than read from `core.yaml` so it survives
/// every staging overlay (which rewrites `core/core.yaml`). The list covers
/// four categories of false-positive drift:
///
///   - master-sync symlinks (target content differs from the staging blob,
///     which is the symlink-target path string)
///   - self-stamping meta-files (`core/core.yaml` carries the rescue stamp)
///   - user-curated trees not sourced from staging (`core/packages` for
///     hq-packs installs)
///   - runtime / overwrite-only state (`.claude/state`, `companies/_template`)
///
/// Always interpreted as a directory-prefix match (see
/// `path_in_excluded_scope`), so leaf entries here also cover files under
/// the same name without needing a trailing slash.
pub fn excluded_scope_paths() -> Vec<String> {
    [
        ".claude/settings.local.json",
        ".claude/state",
        // Scheduler runtime state under the locked `.claude/` scope: the task
        // store and its lock. The lock carries a sessionId/pid and can arrive
        // via sync stamped with a foreign machine's pid — transient,
        // machine-local, never authored content, never in the upstream tree.
        ".claude/scheduled-tasks",
        ".claude/scheduled_tasks.lock",
        ".claude/audit",     // runtime audit logs; not authored content
        ".claude/worktrees", // Claude Code per-Agent worktree sandboxes
        ".claude/commands",  // legacy — consolidated into .claude/skills/
        ".agents/skills",
        ".codex/claude",
        ".codex/output-style.md",
        "AGENTS.md",
        "core/core.yaml",
        "core/packages",
        "core/workspace", // runtime markers (e.g. .last-archive-run)
        // Generated by `core/scripts/generate-workers-registry.sh` from
        // whatever workers the local HQ has installed (core + personal +
        // packs). Content is a function of the user's install state, not
        // the upstream tree — so every machine has a different file and
        // every upstream-vs-local comparison reports false drift. Mirrors
        // the `core/core.yaml` exclusion's rationale: a meta-file that
        // the rescue regenerates anyway.
        "core/workers/registry.yaml",
        "companies/_template",
    ]
    .iter()
    .map(|s| (*s).to_string())
    .collect()
}

/// True iff the path is an HQ-Sync conflict-resolution artifact
/// (e.g. `.claude/CLAUDE.md.conflict-2026-05-15T15-11-53Z-unknown.md`).
/// These are auto-generated when sync detects a local-vs-cloud divergence
/// and renames the local copy — never authored content, never in staging.
pub fn is_conflict_artifact(path: &str) -> bool {
    // Match `.conflict-` anywhere in the basename (covers both
    // `file.txt.conflict-...` and `dir.conflict-...` forms).
    path.rsplit('/')
        .next()
        .map(|name| name.contains(".conflict-"))
        .unwrap_or(false)
}

/// True iff the path falls under one of the excluded-path entries.
/// Always does prefix matching (regardless of trailing slash): `core/packages`
/// and `core/packages/` both exclude files under that directory tree.
pub fn path_in_excluded_scope(path: &str, excluded: &[String]) -> bool {
    for scope in excluded {
        let prefix = scope.trim_end_matches('/');
        if path == prefix || path.starts_with(&format!("{}/", prefix)) {
            return true;
        }
    }
    false
}

/// True iff the given upstream path (from the GitHub trees response)
/// falls under one of the locked-path prefixes. Trailing-slash entries
/// are dir-prefix matches; non-slash entries are exact-path matches.
pub fn path_in_locked_scope(path: &str, locked: &[String]) -> bool {
    for scope in locked {
        if let Some(prefix) = scope.strip_suffix('/') {
            // Directory scope: prefix-match on the dir + '/' so
            // `core/policies/` doesn't match `core/policies-extra.md`.
            if path == prefix || path.starts_with(&format!("{}/", prefix)) {
                return true;
            }
        } else if path == scope {
            return true;
        }
    }
    false
}

/// Compute git's blob SHA-1 for a byte slice. Git's content-addressable
/// blob hash is `sha1("blob " + content_length_decimal + "\0" + content)`
/// — matches what the GitHub trees API returns as `sha` for blob entries.
pub fn git_blob_sha(content: &[u8]) -> String {
    let mut hasher = Sha1::new();
    hasher.update(format!("blob {}\0", content.len()).as_bytes());
    hasher.update(content);
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(40);
    for byte in digest.iter() {
        hex.push_str(&format!("{:02x}", byte));
    }
    hex
}

/// Walk the local HQ folder, restricted to the locked-path scopes, and
/// return a map of relative-path → (sha1, size). Walks files directly
/// for leaf scopes; uses walkdir for directory scopes. Symlinks are
/// followed but never escape the HQ root.
pub fn walk_local_under_scope(
    hq_folder: &Path,
    locked: &[String],
) -> BTreeMap<String, (String, u64)> {
    let mut out = BTreeMap::new();
    for scope in locked {
        let (rel, is_dir) = if let Some(prefix) = scope.strip_suffix('/') {
            (prefix.to_string(), true)
        } else {
            (scope.clone(), false)
        };
        let abs = hq_folder.join(&rel);
        if is_dir {
            if !abs.is_dir() {
                continue;
            }
            for entry in walkdir::WalkDir::new(&abs)
                .follow_links(false)
                .into_iter()
                .filter_map(|e| e.ok())
            {
                if !entry.file_type().is_file() {
                    continue;
                }
                let Ok(rel_path) = entry.path().strip_prefix(hq_folder) else {
                    continue;
                };
                let Ok(content) = std::fs::read(entry.path()) else {
                    continue;
                };
                let size = content.len() as u64;
                let sha = git_blob_sha(&content);
                let rel_str = rel_path.to_string_lossy().replace('\\', "/");
                out.insert(rel_str, (sha, size));
            }
        } else {
            // Leaf scope. Use `symlink_metadata` (NOT `is_file`, which
            // follows symlinks) so master-sync-generated symlinks like
            // `AGENTS.md → .claude/CLAUDE.md` are skipped instead of
            // re-hashed against the target's content. Git stores a symlink
            // as a content blob of its target-path string, not the target's
            // content, so following the symlink yields a wrong SHA every
            // time. Symlinks in directory scopes are already skipped by the
            // walkdir `is_file()` filter above; this is the leaf-scope twin.
            let Ok(meta) = abs.symlink_metadata() else {
                continue;
            };
            if meta.file_type().is_symlink() || !meta.file_type().is_file() {
                continue;
            }
            if let Ok(content) = std::fs::read(&abs) {
                let size = content.len() as u64;
                let sha = git_blob_sha(&content);
                out.insert(rel.clone(), (sha, size));
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn git_blob_sha_matches_git_format() {
        // Empty blob's SHA-1 is the canonical e69de29bb2d1d6434b8b29ae775ad8c2e48c5391.
        let empty = git_blob_sha(b"");
        assert_eq!(empty, "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391");

        // "hello\n" blob's SHA-1 is ce013625030ba8dba906f756967f9e9ca394464a.
        let hello = git_blob_sha(b"hello\n");
        assert_eq!(hello, "ce013625030ba8dba906f756967f9e9ca394464a");
    }

    #[test]
    fn locked_scope_matches_dir_prefix_and_exact_file() {
        let locked = vec![
            "core/policies/".to_string(),
            ".claude/CLAUDE.md".to_string(),
        ];
        // Dir-prefix matches.
        assert!(path_in_locked_scope("core/policies/foo.md", &locked));
        assert!(path_in_locked_scope("core/policies/sub/bar.md", &locked));
        assert!(path_in_locked_scope("core/policies", &locked));
        // Dir-prefix must not bleed onto sibling paths.
        assert!(!path_in_locked_scope("core/policies-extra.md", &locked));
        // Exact-file match.
        assert!(path_in_locked_scope(".claude/CLAUDE.md", &locked));
        // Anchored — substring of an exact-file scope shouldn't match.
        assert!(!path_in_locked_scope(".claude/CLAUDE.md.bak", &locked));
        // Out of scope.
        assert!(!path_in_locked_scope("workspace/threads/foo.json", &locked));
    }

    #[test]
    fn scheduler_lock_and_store_are_excluded_from_drift() {
        // Regression: the transient scheduler lock + task store live under the
        // locked `.claude/` scope but are runtime/machine-local state (the lock
        // even carries a foreign sessionId/pid after a sync), never authored and
        // never shipped upstream — so they must not surface as "Added" drift.
        let excluded = excluded_scope_paths();
        assert!(path_in_excluded_scope(
            ".claude/scheduled_tasks.lock",
            &excluded
        ));
        assert!(path_in_excluded_scope(".claude/scheduled-tasks", &excluded));
        assert!(path_in_excluded_scope(
            ".claude/scheduled-tasks/job-123.json",
            &excluded
        ));
        // Existing exclusions still hold (guards against list churn).
        assert!(path_in_excluded_scope(
            ".claude/settings.local.json",
            &excluded
        ));
        // A genuinely-authored locked file is NOT excluded.
        assert!(!path_in_excluded_scope(".claude/CLAUDE.md", &excluded));
    }
}
