<script lang="ts">
  const conversations = [
    { id:'group', initials:'3', title:'Jacob Posel, Alan Saura', subtitle:'3 people', unread:1 },
    { id:'yousuf', initials:'YK', title:'Yousuf Kalim', subtitle:'Direct message', unread:0 },
    { id:'core', initials:'#', title:'hq-core', subtitle:'Indigo channel', unread:6 },
    { id:'agent', initials:'⚡', title:'Your agent', subtitle:'Personal agent', unread:2 },
    { id:'wins', initials:'#', title:'hq-wins', subtitle:'Indigo channel', unread:0 },
  ];
  let selected=$state('group');let details=$state(true);let draft=$state('');let sent=$state<string[]>([]);let searchOpen=$state(false);
  const active=$derived(conversations.find(c=>c.id===selected)??conversations[0]);
  function send(){if(!draft.trim())return;sent=[...sent,draft.trim()];draft='';}
</script>

<div class="focus-shell variant-enter" class:details-open={details}>
  <aside class="conversation-dock" aria-label="Recent conversations">
    <header><button aria-label="All conversations">☰</button></header>
    <div class="dock-items">{#each conversations as item}<button class:selected={selected===item.id} aria-label={item.title} title={item.title} onclick={()=>selected=item.id}><span>{item.initials}</span>{#if item.unread}<i>{item.unread}</i>{/if}</button>{/each}</div>
    <footer><button aria-label="New message">＋</button></footer>
  </aside>
  <main class="focus-thread">
    <header class="focus-head"><div><small>{active.subtitle}</small><h1>{active.title}</h1></div><div><button class:active={searchOpen} aria-label="Search conversation" onclick={()=>searchOpen=!searchOpen}>⌕</button><button class:active={details} aria-label="Toggle details" onclick={()=>details=!details}>ⓘ</button></div></header>
    {#if searchOpen}<div class="search-bar"><span>⌕</span><input placeholder={`Search in ${active.title}`} /><kbd>esc</kbd></div>{/if}
    <div class="reading-pane">
      <div class="thread-measure">
        <div class="date"><span>Today</span></div>
        <article><header><span class="avatar">JP</span><div><strong>Jacob Posel</strong><time>9:42 AM</time></div></header><p>The Windows updater repair is merged. I’m checking the final release artifacts now.</p><p>Can you verify the Core version resolves after the CLI shim is replaced?</p></article>
        <article><header><span class="avatar">AS</span><div><strong>Alan Saura</strong><time>9:51 AM</time></div></header><p>Verified on a clean Windows install. The app now finds the npm prefix directly and confirms the installed version before completing.</p><blockquote><span>Release check</span><strong>Windows x64 + ARM64 passed</strong><button>View run ↗</button></blockquote></article>
        <article class="mine"><header><span class="avatar">CE</span><div><strong>You</strong><time>10:03 AM</time></div></header><p>Perfect. I’ll post here when stable latest advances.</p></article>
        {#each sent as message}<article class="mine new-message"><header><span class="avatar">CE</span><div><strong>You</strong><time>now</time></div></header><p>{message}</p></article>{/each}
      </div>
    </div>
    <footer class="focus-composer"><div class="composer-box"><textarea bind:value={draft} placeholder={`Message ${active.title}`} onkeydown={(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}}></textarea><div><span><button>＋</button><button>Aa</button><button>☺</button></span><button class="send" disabled={!draft.trim()} onclick={send}>↑</button></div></div></footer>
  </main>
  {#if details}<aside class="details-pane"><header><strong>Conversation</strong><button onclick={()=>details=false}>×</button></header><div class="hero"><span class="hero-avatar">{active.initials}</span><h2>{active.title}</h2><p>{active.subtitle}</p></div><section><h3>People</h3><button><span class="avatar">JP</span><span>Jacob Posel<small>Indigo</small></span></button><button><span class="avatar">AS</span><span>Alan Saura<small>Indigo</small></span></button><button><span class="avatar">CE</span><span>You<small>Owner</small></span></button></section><section><h3>Shared</h3><button class="shared"><span>⌘</span><span>windows-update-smoke.md<small>Today · Jacob</small></span></button></section><footer><button>Mute conversation</button><button>Leave group</button></footer></aside>{/if}
</div>

<style>
  .focus-shell{height:100%;display:grid;grid-template-columns:68px minmax(0,1fr);background:rgba(12,12,12,.24);transition:grid-template-columns 220ms var(--ease-out)}.focus-shell.details-open{grid-template-columns:68px minmax(0,1fr) 258px}button{border:0;background:transparent;cursor:pointer}h1,h2,h3,p{margin:0}
  .conversation-dock{display:grid;grid-template-rows:auto 1fr auto;min-height:0;padding:12px 8px;border-right:1px solid var(--v4-hairline);background:rgba(30,30,30,.54);backdrop-filter:var(--v4-glass-filter)}.conversation-dock header,.conversation-dock footer{display:grid;place-items:center}.conversation-dock button{position:relative;display:grid;place-items:center;width:42px;height:42px;border-radius:50%;color:var(--v4-text-2)}.conversation-dock header button,.conversation-dock footer button{border-radius:var(--v4-radius-button);font-size:18px}.dock-items{min-height:0;display:flex;flex-direction:column;align-items:center;gap:10px;overflow-y:auto;padding-block:16px}.dock-items button>span{display:grid;place-items:center;width:38px;height:38px;border:1px solid var(--v4-control-border);border-radius:50%;background:rgba(255,255,255,.065);font-size:11px;font-weight:650}.dock-items button:hover>span{background:rgba(255,255,255,.1)}.dock-items button.selected>span{background:var(--v4-text-1);color:#111}.dock-items i{position:absolute;right:-2px;top:-2px;min-width:17px;height:17px;padding:0 4px;border:2px solid #222;border-radius:var(--v4-radius-pill);background:var(--v4-text-1);color:#111;font-size:9px;font-style:normal;line-height:13px}
  .focus-thread{min-width:0;min-height:0;display:grid;grid-template-rows:auto auto 1fr auto;background:rgba(13,13,13,.18)}.focus-head{display:flex;align-items:center;min-height:72px;padding:12px 32px;border-bottom:1px solid var(--v4-hairline);background:rgba(18,18,18,.32);backdrop-filter:var(--v4-glass-filter-soft)}.focus-head small{color:var(--v4-text-3);font-size:10px;text-transform:uppercase;letter-spacing:.06em}.focus-head h1{margin-top:3px;font-size:18px;letter-spacing:-.02em}.focus-head>div:last-child{display:flex;gap:5px;margin-left:auto}.focus-head button{width:32px;height:32px;border-radius:var(--v4-radius-button);color:var(--v4-text-2)}.focus-head button:hover,.focus-head button.active{background:var(--v4-control-bg)}
  .search-bar{display:flex;align-items:center;height:42px;padding:0 32px;border-bottom:1px solid var(--v4-rowline);background:rgba(255,255,255,.025);color:var(--v4-text-3);animation:search-in 180ms var(--ease-out) both}.search-bar input{flex:1;margin-left:9px;border:0;outline:0;background:transparent;color:var(--v4-text-1)}kbd{padding:2px 5px;border:1px solid var(--v4-control-border);border-radius:4px;color:var(--v4-text-3);font:10px 'Geist Mono',monospace}
  .reading-pane{min-height:0;overflow-y:auto;padding:32px clamp(34px,8vw,120px)}.thread-measure{max-width:760px;margin:0 auto}.date{display:flex;align-items:center;gap:12px;margin-bottom:28px;color:var(--v4-text-3);font-size:10px;text-transform:uppercase;letter-spacing:.08em}.date::before,.date::after{content:'';flex:1;height:1px;background:var(--v4-rowline)}article{margin-bottom:30px}article header{display:flex;align-items:center;gap:10px}.avatar{display:grid;place-items:center;width:32px;height:32px;border:1px solid var(--v4-control-border);border-radius:50%;background:rgba(255,255,255,.065);font-size:10px;font-weight:650}article header>div{display:grid;gap:2px}article strong{font-size:13px}article time{color:var(--v4-text-3);font-size:10px}article p{margin:8px 0 0 42px;color:var(--v4-text-2);font-size:15px;line-height:1.62}article p+p{margin-top:3px}blockquote{display:flex;align-items:center;gap:10px;margin:14px 0 0 42px;padding:11px 0;border-block:1px solid var(--v4-rowline);font-size:11px}blockquote span{color:var(--v4-text-3)}blockquote strong{font-size:11px}blockquote button{margin-left:auto;color:var(--v4-text-1)}
  .focus-composer{padding:0 clamp(34px,8vw,120px) 18px}.composer-box{max-width:760px;margin:0 auto;border:1px solid var(--v4-control-border);border-radius:var(--v4-radius-card);background:rgba(36,36,36,.64);backdrop-filter:var(--v4-glass-filter-soft);box-shadow:0 14px 34px rgba(0,0,0,.2)}textarea{display:block;width:100%;min-height:58px;resize:none;padding:13px;border:0;outline:0;background:transparent;color:var(--v4-text-1)}.composer-box>div{display:flex;align-items:center;height:38px;padding:0 8px}.composer-box span{display:flex}.composer-box button{width:29px;height:29px;border-radius:var(--v4-radius-button);color:var(--v4-text-3)}.composer-box .send{margin-left:auto;border-radius:50%;background:var(--v4-text-1);color:#111;font-size:17px}.send:disabled{opacity:.3}
  .details-pane{min-height:0;display:flex;flex-direction:column;border-left:1px solid var(--v4-hairline);background:rgba(30,30,30,.48);backdrop-filter:var(--v4-glass-filter);animation:details-in 200ms var(--ease-out) both;transform-origin:right center}.details-pane>header{display:flex;align-items:center;height:54px;padding:0 16px;border-bottom:1px solid var(--v4-rowline);font-size:12px}.details-pane>header button{margin-left:auto;color:var(--v4-text-3);font-size:18px}.hero{display:grid;justify-items:center;padding:24px 16px;border-bottom:1px solid var(--v4-rowline)}.hero-avatar{display:grid;place-items:center;width:54px;height:54px;border:1px solid var(--v4-control-border);border-radius:50%;background:rgba(255,255,255,.075);font-size:15px;font-weight:650}.hero h2{margin-top:10px;font-size:14px;text-align:center}.hero p{margin-top:3px;color:var(--v4-text-3);font-size:11px}.details-pane section{padding:18px 14px;border-bottom:1px solid var(--v4-rowline)}.details-pane h3{margin:0 4px 9px;color:var(--v4-text-3);font-size:10px;letter-spacing:.07em;text-transform:uppercase}.details-pane section button{display:flex;align-items:center;width:100%;gap:9px;padding:6px 4px;border-radius:var(--v4-radius-button);text-align:left}.details-pane section button>span:last-child{display:grid;font-size:11px}.details-pane section small{color:var(--v4-text-3);font-size:9px}.shared>span:first-child{font-size:18px}.details-pane>footer{display:grid;gap:3px;margin-top:auto;padding:12px}.details-pane>footer button{height:31px;border-radius:var(--v4-radius-button);color:var(--v4-text-3);text-align:left}.details-pane>footer button:hover{background:var(--v4-control-bg);color:var(--v4-text-2)}
  .variant-enter{animation:variant-in 220ms var(--ease-out) both}.new-message{animation:message-in 220ms var(--ease-out) both}@keyframes variant-in{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}@keyframes details-in{from{opacity:0;transform:translateX(8px)}to{opacity:1;transform:none}}@keyframes search-in{from{opacity:0;transform:translateY(-4px)}to{opacity:1;transform:none}}@keyframes message-in{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){.focus-shell,.variant-enter,.details-pane,.search-bar,.new-message{animation:none;transition:none}}@media(max-width:1240px){.focus-shell.details-open{grid-template-columns:68px minmax(0,1fr)}.details-pane{display:none}.reading-pane,.focus-composer{padding-inline:42px}}
</style>
